/*

 SMALLMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\gbdk\tools\GBTD\world11_set.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __SmallMap_h_INCLUDE
#define __SmallMap_h_INCLUDE

#define SmallMapWidth 20
#define SmallMapHeight 18
#define SmallMapBank 0

extern const unsigned char SmallMap[];

#endif

/* End of SMALLMAP.H */
