/*

 WORLDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 422 x 60
   Tile set      : D:\gbdk\tools\GBTD\world11_set.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __WorldMap_h_INCLUDE
#define __WorldMap_h_INCLUDE

#define WorldMapWidth 422
#define WorldMapHeight 60
#define WorldMapBank 0

extern const unsigned char WorldMap[];

#endif

/* End of WORLDMAP.H */
