/*
 FONTTILES.H

 SMB font, one tile per character in FONT_CHARS ('x' is the times sign, '@' the coin).

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __FontTiles_h_INCLUDE
#define __FontTiles_h_INCLUDE

#include <gbdk/platform.h>

#define FontTilesCount 41


// In a switchable ROM bank: switch to BANK(FontTiles) before reading it
BANKREF_EXTERN(FontTiles)
extern const unsigned char FontTiles[];

// Character for each tile, in order
#define FONT_CHARS " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-x!@"

#endif
