/*
 MISCBACKGROUNDTILES.H

 Background tiles not used by any named sheet (NES title logo pieces, unused tiles), in NES tile order. Each comment gives the NES tile number.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __MiscBackgroundTiles_h_INCLUDE
#define __MiscBackgroundTiles_h_INCLUDE

#include <gbdk/platform.h>

#define MiscBackgroundTilesCount 64

#define MISCBACKGROUNDTILES_FIRST      0

// In a switchable ROM bank: switch to BANK(MiscBackgroundTiles) before reading it
BANKREF_EXTERN(MiscBackgroundTiles)
extern const unsigned char MiscBackgroundTiles[];

#endif
