/*
 SCENERYTILES.H

 Every 16x16 background block (metatile) Super Mario Bros. can draw: overworld,
 underground, castle, water and sky scenery, blocks, pipes, bridges, the axe...
 SceneryTiles holds the unique 8x8 tiles; SceneryMetatiles holds 4 tile indexes
 per block (TL, TR, BL, BR) and SCENERY_<NAME> is a block's number in it.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __SceneryTiles_h_INCLUDE
#define __SceneryTiles_h_INCLUDE

#include <gbdk/platform.h>

#define SceneryTilesCount 156
#define SceneryMetatileCount 101

#define SCENERY_BLANK                        0
#define SCENERY_BLACK                        1
#define SCENERY_BUSH_LEFT                    2
#define SCENERY_BUSH_MIDDLE                  3
#define SCENERY_BUSH_RIGHT                   4
#define SCENERY_HILL_LEFT                    5
#define SCENERY_HILL_LEFT_BOTTOM             6
#define SCENERY_HILL_TOP                     7
#define SCENERY_HILL_RIGHT                   8
#define SCENERY_HILL_RIGHT_BOTTOM            9
#define SCENERY_HILL_BOTTOM                 10
#define SCENERY_BRIDGE_RAIL                 11
#define SCENERY_CHAIN                       12
#define SCENERY_TALL_TREE_TOP               13
#define SCENERY_SHORT_TREE                  14
#define SCENERY_TALL_TREE_BOTTOM            15
#define SCENERY_PIPE_TOP_LEFT               16
#define SCENERY_PIPE_TOP_RIGHT              17
#define SCENERY_DECOR_PIPE_TOP_LEFT         18
#define SCENERY_DECOR_PIPE_TOP_RIGHT        19
#define SCENERY_PIPE_LEFT                   20
#define SCENERY_PIPE_RIGHT                  21
#define SCENERY_TREE_LEDGE_LEFT             22
#define SCENERY_TREE_LEDGE_MIDDLE           23
#define SCENERY_TREE_LEDGE_RIGHT            24
#define SCENERY_MUSHROOM_LEFT               25
#define SCENERY_MUSHROOM_MIDDLE             26
#define SCENERY_MUSHROOM_RIGHT              27
#define SCENERY_SIDE_PIPE_END_TOP           28
#define SCENERY_SIDE_PIPE_TOP               29
#define SCENERY_SIDE_PIPE_JOINT_TOP         30
#define SCENERY_SIDE_PIPE_END_BOTTOM        31
#define SCENERY_SIDE_PIPE_BOTTOM            32
#define SCENERY_SIDE_PIPE_JOINT_BOTTOM      33
#define SCENERY_SEAPLANT                    34
#define SCENERY_BLANK_HIT                   35
#define SCENERY_FLAGPOLE_BALL               36
#define SCENERY_FLAGPOLE                    37
#define SCENERY_BLANK_VINE                  38
#define SCENERY_ROPE_VERTICAL               39
#define SCENERY_ROPE_HORIZONTAL             40
#define SCENERY_PULLEY_LEFT                 41
#define SCENERY_PULLEY_RIGHT                42
#define SCENERY_BLANK_ROPE                  43
#define SCENERY_CASTLE_TOP                  44
#define SCENERY_CASTLE_WINDOW_LEFT          45
#define SCENERY_CASTLE_WALL                 46
#define SCENERY_CASTLE_WINDOW_RIGHT         47
#define SCENERY_CASTLE_TOP_BRICK            48
#define SCENERY_CASTLE_DOOR_TOP             49
#define SCENERY_CASTLE_DOOR                 50
#define SCENERY_LEDGE_STUMP                 51
#define SCENERY_FENCE                       52
#define SCENERY_TREE_TRUNK                  53
#define SCENERY_MUSHROOM_STUMP_TOP          54
#define SCENERY_MUSHROOM_STUMP              55
#define SCENERY_BRICK_LINE                  56
#define SCENERY_BRICK                       57
#define SCENERY_BRICK_UNUSED                58
#define SCENERY_ROCK                        59
#define SCENERY_BRICK_LINE_POWERUP          60
#define SCENERY_BRICK_LINE_VINE             61
#define SCENERY_BRICK_LINE_STAR             62
#define SCENERY_BRICK_LINE_COINS            63
#define SCENERY_BRICK_LINE_1UP              64
#define SCENERY_BRICK_POWERUP               65
#define SCENERY_BRICK_VINE                  66
#define SCENERY_BRICK_STAR                  67
#define SCENERY_BRICK_COINS                 68
#define SCENERY_BRICK_1UP                   69
#define SCENERY_HIDDEN_COIN                 70
#define SCENERY_HIDDEN_1UP                  71
#define SCENERY_STAIR_BLOCK                 72
#define SCENERY_WHITE_WALL                  73
#define SCENERY_BRIDGE                      74
#define SCENERY_CANNON_BARREL               75
#define SCENERY_CANNON_TOP                  76
#define SCENERY_CANNON_BOTTOM               77
#define SCENERY_BLANK_SPRING                78
#define SCENERY_HALF_BRICK_SPRING           79
#define SCENERY_WATER_ROCK                  80
#define SCENERY_HALF_BRICK                  81
#define SCENERY_WATER_PIPE_TOP              82
#define SCENERY_WATER_PIPE_BOTTOM           83
#define SCENERY_FLAG_BALL                   84
#define SCENERY_CLOUD_LEFT                  85
#define SCENERY_CLOUD_MIDDLE                86
#define SCENERY_CLOUD_RIGHT                 87
#define SCENERY_CLOUD_BOTTOM_LEFT           88
#define SCENERY_CLOUD_BOTTOM_MIDDLE         89
#define SCENERY_CLOUD_BOTTOM_RIGHT          90
#define SCENERY_WATER_TOP                   91
#define SCENERY_WATER                       92
#define SCENERY_CLOUD_GROUND                93
#define SCENERY_BOWSER_BRIDGE               94
#define SCENERY_QUESTION_COIN               95
#define SCENERY_QUESTION_POWERUP            96
#define SCENERY_COIN                        97
#define SCENERY_WATER_COIN                  98
#define SCENERY_USED_BLOCK                  99
#define SCENERY_AXE                        100

// In a switchable ROM bank: switch to BANK(SceneryTiles) before reading either array
BANKREF_EXTERN(SceneryTiles)
extern const unsigned char SceneryTiles[];
extern const unsigned char SceneryMetatiles[];

#endif
