/*
 LEVELINFO.H

 Things about each level from Super Mario Bros.' own tables. The halfway point
 (HalfwayPageNybbles) is a page (16 blocks): once the screen has scrolled that
 far, dying restarts the level from there instead of the beginning.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __LevelInfo_h_INCLUDE
#define __LevelInfo_h_INCLUDE

#define LEVEL1_1_HALFWAY_PAGE 5
#define LEVEL1_2_HALFWAY_PAGE 6

#endif
