/*
 LEVEL1_1ENEMIES.H

 Where World 1-1's enemies start, read from Super Mario Bros.' own enemy list.
 4 bytes each: x (low, high) and y in level pixels (top-left of the 16x16
 body, standing on the ground or a platform), then the ENEMY_* type.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __Level1_1Enemies_h_INCLUDE
#define __Level1_1Enemies_h_INCLUDE

#include <gbdk/platform.h>

#define ENEMY_GOOMBA 0
#define ENEMY_KOOPA 1

#define Level1_1EnemyCount 17

// In switchable ROM bank 1 (maps): switch to BANK(Level1_1Enemies) before reading it
BANKREF_EXTERN(Level1_1Enemies)
extern const unsigned char Level1_1Enemies[];

#endif
