/*
 LEVEL1_1ENEMIES.C

 See Level1_1Enemies.h.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/

#pragma bank 1

#include <gbdk/platform.h>

BANKREF(Level1_1Enemies)

const unsigned char Level1_1Enemies[] =
{
  0x60,0x01, 192, 0, // goomba at block 22
  0x80,0x02, 192, 0, // goomba at block 40
  0x60,0x03, 192, 0, // goomba at block 54
  0x78,0x03, 192, 0, // goomba at block 55.5
  0x00,0x05,  64, 0, // goomba at block 80
  0x20,0x05,  64, 0, // goomba at block 82
  0x40,0x06, 192, 0, // goomba at block 100
  0x58,0x06, 192, 0, // goomba at block 101.5
  0xB0,0x06, 192, 1, // koopa at block 107
  0x50,0x07, 192, 0, // goomba at block 117
  0x68,0x07, 192, 0, // goomba at block 118.5
  0xF0,0x07, 192, 0, // goomba at block 127
  0x08,0x08, 192, 0, // goomba at block 128.5
  0x30,0x08, 192, 0, // goomba at block 131
  0x48,0x08, 192, 0, // goomba at block 132.5
  0x10,0x0B, 192, 0, // goomba at block 177
  0x28,0x0B, 192, 0, // goomba at block 178.5
};
