/*
 LEVELENEMIES.H

 Where each level's enemies start, read from Super Mario Bros.' own enemy lists.
 4 bytes each, sorted by x: x (low, high) and y in level pixels (the top-left of
 the body, standing on the ground or a platform; a Piranha Plant's is inside its
 pipe, a lift's its top), then the ENEMY_* type.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __LevelEnemies_h_INCLUDE
#define __LevelEnemies_h_INCLUDE

#include <gbdk/platform.h>

#define ENEMY_GOOMBA     0
#define ENEMY_KOOPA      1
#define ENEMY_RED_KOOPA  2
#define ENEMY_PIRANHA    3
#define ENEMY_LIFT_UP    4
#define ENEMY_LIFT_DOWN  5

#define Level1_1EnemiesCount 17
extern const unsigned char Level1_1Enemies[];
#define Level1_2EnemiesCount 25
extern const unsigned char Level1_2Enemies[];

// In switchable ROM bank 1 (maps): switch to BANK(LevelEnemies) before reading them
BANKREF_EXTERN(LevelEnemies)

#endif
