/*
 LEVEL1_2.H

 World 1-2, read from Super Mario Bros.' own level data.

 A grid of 16x16 blocks (SCENERY_* numbers), 199 wide by 15 tall, row by row.
 Block rows are the map's (SMB's rows 0-12 are its rows 2-14).

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __Level1_2_h_INCLUDE
#define __Level1_2_h_INCLUDE

#include <gbdk/platform.h>

#define Level1_2Width 199
#define Level1_2Height 15

// Where Mario drops in (level pixels: his left, and his feet)
#define LEVEL1_2_START_X 32
#define LEVEL1_2_START_FEET 64
// The way out: the sideways pipe's mouth (block column, block row of its top half),
#define LEVEL1_2_EXIT_COLUMN 166
#define LEVEL1_2_EXIT_ROW 8
// which comes out of 1-1's pipe here (SMB reuses 1-1's end for 1-2's)
#define LEVEL1_2_EXIT_PIPE_COLUMN 179
#define LEVEL1_2_EXIT_PIPE_ROW 11
// The warp zone: its text starts at this block column, and its pipes (to worlds 4, 3, 2)
#define LEVEL1_2_WARP_ZONE_COLUMN 178
#define LEVEL1_2_WARP_PIPE1_COLUMN 178
#define LEVEL1_2_WARP_PIPE2_COLUMN 182
#define LEVEL1_2_WARP_PIPE3_COLUMN 186
#define LEVEL1_2_WARP_PIPE_ROW 10

// In switchable ROM bank 1 (maps): switch to BANK(Level1_2) before reading it
BANKREF_EXTERN(Level1_2)
extern const unsigned char Level1_2[];

#endif
