/*
 LEVELENEMIES.C

 See LevelEnemies.h.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/

#pragma bank 1

#include <gbdk/platform.h>

BANKREF(LevelEnemies)

// World 1-1
const unsigned char Level1_1Enemies[] =
{
  0x60,0x01, 192, 0, // goomba at block 22
  0x80,0x02, 192, 0, // goomba at block 40
  0x60,0x03, 192, 0, // goomba at block 54
  0x78,0x03, 192, 0, // goomba at block 55.5
  0x00,0x05,  64, 0, // goomba at block 80
  0x20,0x05,  64, 0, // goomba at block 82
  0x40,0x06, 192, 0, // goomba at block 100
  0x58,0x06, 192, 0, // goomba at block 101.5
  0xB0,0x06, 192, 1, // koopa at block 107
  0x50,0x07, 192, 0, // goomba at block 117
  0x68,0x07, 192, 0, // goomba at block 118.5
  0xF0,0x07, 192, 0, // goomba at block 127
  0x08,0x08, 192, 0, // goomba at block 128.5
  0x30,0x08, 192, 0, // goomba at block 131
  0x48,0x08, 192, 0, // goomba at block 132.5
  0x10,0x0B, 192, 0, // goomba at block 177
  0x28,0x0B, 192, 0, // goomba at block 178.5
};

// World 1-2
const unsigned char Level1_2Enemies[] =
{
  0x00,0x01, 192, 0, // goomba at block 16
  0x10,0x01, 176, 0, // goomba at block 17
  0xD0,0x01, 192, 0, // goomba at block 29
  0xF0,0x02, 192, 1, // koopa at block 47
  0x08,0x03, 192, 1, // koopa at block 48.5
  0xB0,0x03, 192, 1, // koopa at block 59
  0xE0,0x03, 192, 0, // goomba at block 62
  0x00,0x04, 192, 0, // goomba at block 64
  0x90,0x04,  64, 0, // goomba at block 73
  0xF0,0x04, 128, 0, // goomba at block 79
  0x08,0x05, 128, 0, // goomba at block 80.5
  0x78,0x06, 160, 3, // piranha at block 103.5
  0xD8,0x06, 144, 3, // piranha at block 109.5
  0x38,0x07, 176, 3, // piranha at block 115.5
  0x60,0x07, 192, 0, // goomba at block 118
  0x78,0x07, 192, 0, // goomba at block 119.5
  0x90,0x07, 192, 0, // goomba at block 121
  0x10,0x08, 192, 0, // goomba at block 129
  0xA0,0x09, 128, 0, // goomba at block 154
  0xB0,0x09, 128, 4, // lift_up at block 155
  0xB0,0x09, 224, 4, // lift_up at block 155
  0xB8,0x09, 128, 0, // goomba at block 155.5
  0x20,0x0A, 192, 2, // red_koopa at block 162
  0xA0,0x0A,  32, 5, // lift_down at block 170
  0xA0,0x0A, 160, 5, // lift_down at block 170
};
