/*
 LEVEL1_1BONUS.H

 World 1-1's underground coin room, read from Super Mario Bros.' own level data,
 as a grid of 16x16 blocks (SCENERY_* numbers) 20 wide by 15 tall, row by row,
 and where the pipes in and out of it are.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __Level1_1Bonus_h_INCLUDE
#define __Level1_1Bonus_h_INCLUDE

#include <gbdk/platform.h>

#define Level1_1BonusWidth 20
#define Level1_1BonusHeight 15

// 1-1's pipe that leads here: its left block column, and the block row of its top
#define LEVEL1_1_PIPE_COLUMN 57
#define LEVEL1_1_PIPE_ROW 9

// Where Mario drops into the room (level pixels, top-left)
#define LEVEL1_1_BONUS_START_X 32
#define LEVEL1_1_BONUS_START_Y 32

// The way out: the sideways pipe's mouth (block column, block row of its top half)
#define LEVEL1_1_BONUS_EXIT_COLUMN 13
#define LEVEL1_1_BONUS_EXIT_ROW 11

// ...which leads back to 1-1's pipe here (left block column, block row of its top)
#define LEVEL1_1_RETURN_PIPE_COLUMN 163
#define LEVEL1_1_RETURN_PIPE_ROW 11

// In switchable ROM bank 1 (maps): switch to BANK(Level1_1Bonus) before reading it
BANKREF_EXTERN(Level1_1Bonus)
extern const unsigned char Level1_1Bonus[];

#endif
