/*
 LEVEL1_2BONUS.H

 World 1-2's underground coin room, read from Super Mario Bros.' own level data,
 and where the pipes in and out of it are.

 A grid of 16x16 blocks (SCENERY_* numbers), 20 wide by 15 tall, row by row.
 Block rows are the map's (SMB's rows 0-12 are its rows 2-14).

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __Level1_2Bonus_h_INCLUDE
#define __Level1_2Bonus_h_INCLUDE

#include <gbdk/platform.h>

#define Level1_2BonusWidth 20
#define Level1_2BonusHeight 15

// 1-2's pipe that leads here: its left block column, and the block row of its top
#define LEVEL1_2_PIPE_COLUMN 103
#define LEVEL1_2_PIPE_ROW 10
// Where Mario drops into the room (level pixels: his left, and his feet)
#define LEVEL1_2_BONUS_START_X 32
#define LEVEL1_2_BONUS_START_FEET 64
// The way out: the sideways pipe's mouth (block column, block row of its top half)
#define LEVEL1_2_BONUS_EXIT_COLUMN 13
#define LEVEL1_2_BONUS_EXIT_ROW 11
// ...which leads back to 1-2's pipe here (left block column, block row of its top)
#define LEVEL1_2_RETURN_PIPE_COLUMN 115
#define LEVEL1_2_RETURN_PIPE_ROW 11

// In switchable ROM bank 1 (maps): switch to BANK(Level1_2Bonus) before reading it
BANKREF_EXTERN(Level1_2Bonus)
extern const unsigned char Level1_2Bonus[];

#endif
