/*
 LEVEL1_2INTRO.H

 World 1-2's intro, read from Super Mario Bros.' own level data: Mario walks
 from the castle into the pipe (the level itself is underground, Level1_2).

 A grid of 16x16 blocks (SCENERY_* numbers), 20 wide by 15 tall, row by row.
 Block rows are the map's (SMB's rows 0-12 are its rows 2-14).

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __Level1_2Intro_h_INCLUDE
#define __Level1_2Intro_h_INCLUDE

#include <gbdk/platform.h>

#define Level1_2IntroWidth 20
#define Level1_2IntroHeight 15

// Where Mario starts (level pixels: his left, and his feet)
#define LEVEL1_2_INTRO_START_X 32
#define LEVEL1_2_INTRO_START_FEET 208
// The pipe he walks into: its mouth (block column, block row of its top half)
#define LEVEL1_2_INTRO_PIPE_COLUMN 10
#define LEVEL1_2_INTRO_PIPE_ROW 11

// In switchable ROM bank 1 (maps): switch to BANK(Level1_2Intro) before reading it
BANKREF_EXTERN(Level1_2Intro)
extern const unsigned char Level1_2Intro[];

#endif
