"""Extract Super Mario Bros. (NES) graphics into GBDK assets.

Usage:  python tools/nes2gb.py path/to/SuperMarioBros.nes

The ROM itself is never copied into the project; only the converted tiles are
written, to assets/sprites and assets/tiles. Rerun after changing anything here.

It also writes references/<Sheet>.png: every tile sheet in assets/, each
tile shown in Game Boy grays with its index in the sheet below it.

NES and Game Boy tiles are both 8x8 with 2 bits per pixel, but the NES stores
all 8 rows of bitplane 0 followed by bitplane 1, while the Game Boy interleaves
the two planes row by row. The NES also colors each tile through a palette, so
every asset below says how its 4 NES color indexes map to the Game Boy's
4 grays (0 = white / transparent on sprites, 1 = light, 2 = dark, 3 = black).

Tile numbers and layouts come from the game's own tables (see the SMB
disassembly: PlayerGraphicsTable, EnemyGraphicsTable, PowerUpGfxTable,
JumpingCoinTiles, FloateyNumTileData, and the metatile graphics tables).
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Every sheet lives in this ROM bank; code gets it with BANK(<sheet name>)
GRAPHICS_BANK = 2
PRG_SIZE = 32768
CHR_SIZE = 8192
SPR = 0x000  # sprite pattern table
BG = 0x100   # background pattern table

# NES color index -> Game Boy gray
SPRITE_GRAYS = {0: 0, 1: 2, 2: 1, 3: 3}  # red -> dark, skin/tan -> light, brown -> black
TEXT_GRAYS = {0: 0, 1: 3, 2: 3, 3: 3}    # any ink -> black on the white sky
BACKGROUND_GRAYS = {0: 0, 1: 1, 2: 2, 3: 3}  # sky -> white, then light to dark as on the NES


def load_rom(path):
    """(CHR tile data, PRG program data)"""
    data = open(path, 'rb').read()
    if data[:4] != b'NES\x1a' or data[4] != 2 or data[5] != 1:
        sys.exit("%s doesn't look like the Super Mario Bros. NES ROM (NROM, 32K PRG + 8K CHR)" % path)
    start = 16 + PRG_SIZE
    return data[start:start + CHR_SIZE], data[16:start]


class Chr:
    def __init__(self, data, prg):
        self.data = data
        self.prg = prg
        self.used = set()  # tiles the named sheets use, so leftovers go in the Misc sheets

    def tile(self, index):
        """8x8 list of NES color indexes"""
        self.used.add(index)
        b = self.data[index * 16:index * 16 + 16]
        return [[((b[y] >> (7 - x)) & 1) | (((b[y + 8] >> (7 - x)) & 1) << 1) for x in range(8)] for y in range(8)]


def hflip(t):
    return [row[::-1] for row in t]


def vflip(t):
    return t[::-1]


def to_gb(t, grays):
    """Game Boy 2bpp bytes (low plane, high plane per row)"""
    out = []
    for row in t:
        lo = hi = 0
        for x, v in enumerate(row):
            g = grays[v]
            if g & 1:
                lo |= 0x80 >> x
            if g & 2:
                hi |= 0x80 >> x
        out += [lo, hi]
    return out


class Asset:
    """Collects tiles plus a named index for each frame, then writes .c/.h"""

    def __init__(self, name, description):
        self.name = name
        self.description = description
        self.tiles = []     # (bytes, comment)
        self.defines = []   # (name, value, comment)

    def add(self, label, tiles, grays, comment=""):
        self.defines.append(("%s_%s" % (self.name.upper(), label), len(self.tiles), comment))
        for i, t in enumerate(tiles):
            self.tiles.append((to_gb(t, grays), "%s %d" % (label.lower(), i)))

    def write(self, folder, extra_h=""):
        guard = "__%s_h_INCLUDE" % self.name
        h = ["/*", " %s.H" % self.name.upper(), "", " " + self.description, "",
             " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
             " Do not edit; change the script and rerun it.", "*/",
             "#ifndef %s" % guard, "#define %s" % guard, "",
             "#include <gbdk/platform.h>", "",
             "#define %sCount %d" % (self.name, len(self.tiles)), ""]
        for name, value, comment in self.defines:
            h.append("#define %-28s %3d%s" % (name, value, ("  // " + comment) if comment else ""))
        h += ["", "// In a switchable ROM bank: switch to BANK(%s) before reading it" % self.name,
              "BANKREF_EXTERN(%s)" % self.name, "extern const unsigned char %s[];" % self.name]
        if extra_h:
            h += ["", extra_h]
        h += ["", "#endif", ""]
        c = ["/*", " %s.C" % self.name.upper(), "", " " + self.description, "",
             " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
             " Do not edit; change the script and rerun it.", "*/", "",
             "#pragma bank %d" % GRAPHICS_BANK, "", "#include <gbdk/platform.h>", "",
             "BANKREF(%s)" % self.name, "",
             "const unsigned char %s[] =" % self.name, "{"]
        for data, comment in self.tiles:
            c.append("  " + ",".join("0x%02X" % b for b in data) + ", // " + comment)
        c += ["};", ""]
        base = os.path.join(ROOT, folder, self.name)
        open(base + ".h", "w", newline="\n").write("\n".join(h))
        open(base + ".c", "w", newline="\n").write("\n".join(c))
        print("wrote %s.c/.h (%d tiles)" % (os.path.join(folder, self.name), len(self.tiles)))


def frame16(chr_, tl, tr, bl, br, mirror_right=False):
    """16x16 frame in metasprite order: TL, BL, TR, BR (column by column).
    SMB draws a repeated left/right tile mirrored on the right."""
    t_tr = hflip(chr_.tile(tl)) if (mirror_right or tl == tr) else chr_.tile(tr)
    t_br = hflip(chr_.tile(bl)) if (mirror_right or bl == br) else chr_.tile(br)
    return [chr_.tile(tl), chr_.tile(bl), t_tr, t_br]


def frame16x32(chr_, rows):
    """16x32 frame from 4 (left, right) rows, returned row by row: TL, TR, ..."""
    out = []
    for left, right in rows:
        out.append(chr_.tile(left))
        out.append(hflip(chr_.tile(left)) if left == right else chr_.tile(right))
    return out


def render_references():
    """references/<Sheet>.png for every tile sheet in assets/: each tile at 4x
    in Game Boy grays, with its index in the sheet written below it"""
    import glob
    import re
    from PIL import Image, ImageDraw

    out_dir = os.path.join(ROOT, "references")
    os.makedirs(out_dir, exist_ok=True)
    grays = [(255, 255, 255), (170, 170, 170), (85, 85, 85), (0, 0, 0)]
    scale, columns = 4, 16
    cell_w, cell_h = 8 * scale + 8, 8 * scale + 14

    for path in sorted(glob.glob(os.path.join(ROOT, "assets", "*", "*.c"))):
        text = open(path).read()
        match = re.search(r"const unsigned char (\w*Tiles)\[\] =\s*\{(.*?)\};", text, re.S)
        if not match:
            continue  # not a tile sheet (maps, metasprites)
        name = match.group(1)
        body = re.sub(r"//[^\n]*", "", match.group(2))
        data = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body)]
        count = len(data) // 16
        rows = (count + columns - 1) // columns
        sheet = Image.new("RGB", (columns * cell_w + 4, rows * cell_h + 4), (200, 220, 255))
        draw = ImageDraw.Draw(sheet)
        for i in range(count):
            x0 = 4 + (i % columns) * cell_w
            y0 = 4 + (i // columns) * cell_h
            tile = Image.new("RGB", (8, 8))
            for y in range(8):
                lo, hi = data[i * 16 + y * 2], data[i * 16 + y * 2 + 1]
                for x in range(8):
                    tile.putpixel((x, y), grays[((lo >> (7 - x)) & 1) | (((hi >> (7 - x)) & 1) << 1)])
            sheet.paste(tile.resize((8 * scale, 8 * scale), Image.NEAREST), (x0, y0))
            label = str(i)
            draw.text((x0 + (8 * scale - 6 * len(label)) // 2, y0 + 8 * scale + 1), label, fill=(0, 0, 0))
        sheet.save(os.path.join(out_dir, name + ".png"))
    print("wrote references/*.png")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        sys.exit(__doc__)
    chr_ = Chr(*load_rom(args[0]))
    s = lambda i: SPR + i
    b = lambda i: BG + i
    t = lambda i: chr_.tile(s(i))
    mirror4 = lambda i: [t(i), vflip(t(i)), hflip(t(i)), hflip(vflip(t(i)))]  # TL, BL, TR, BR

    # ---- Small Mario: 16x16 frames, same order the existing metasprites use (PlayerGraphicsTable)
    mario = Asset("MarioTiles", "Small Mario. 4 tiles per 16x16 frame: TL, BL, TR, BR.")
    mario.add("STAND", frame16(chr_, s(0x3A), s(0x37), s(0x4F), s(0x4F)), SPRITE_GRAYS)
    mario.add("WALK1", frame16(chr_, s(0x32), s(0x33), s(0x34), s(0x35)), SPRITE_GRAYS)
    mario.add("WALK2", frame16(chr_, s(0x36), s(0x37), s(0x38), s(0x39)), SPRITE_GRAYS)
    mario.add("WALK3", frame16(chr_, s(0x3A), s(0x37), s(0x3B), s(0x3C)), SPRITE_GRAYS)
    mario.add("JUMP", frame16(chr_, s(0x32), s(0x41), s(0x42), s(0x43)), SPRITE_GRAYS)
    mario.add("SKID", frame16(chr_, s(0x3D), s(0x3E), s(0x3F), s(0x40)), SPRITE_GRAYS)
    mario.add("DEAD", frame16(chr_, s(0x9E), s(0x9E), s(0x9F), s(0x9F)), SPRITE_GRAYS)
    mario.add("SWIM1", frame16(chr_, s(0x32), s(0x33), s(0x44), s(0x45)), SPRITE_GRAYS)
    mario.add("SWIM2", frame16(chr_, s(0x32), s(0x33), s(0x44), s(0x47)), SPRITE_GRAYS)
    mario.add("SWIM3", frame16(chr_, s(0x32), s(0x33), s(0x48), s(0x49)), SPRITE_GRAYS)
    mario.add("CLIMB1", frame16(chr_, s(0x32), s(0x33), s(0x90), s(0x91)), SPRITE_GRAYS)
    mario.add("CLIMB2", frame16(chr_, s(0x3A), s(0x37), s(0x92), s(0x93)), SPRITE_GRAYS)
    mario.write("assets/sprites")

    # ---- Big Mario (also Fire Mario: same tiles, different NES palette)
    big = Asset("BigMarioTiles", "Big / Fire Mario. 8 tiles per 16x32 frame, row by row: TL, TR, then down.")
    for label, rows in (
            ("STAND", [(0x00, 0x01), (0x4C, 0x4D), (0x4A, 0x4A), (0x4B, 0x4B)]),
            ("WALK1", [(0x00, 0x01), (0x02, 0x03), (0x04, 0x05), (0x06, 0x07)]),
            ("WALK2", [(0x08, 0x09), (0x0A, 0x0B), (0x0C, 0x0D), (0x0E, 0x0F)]),
            ("WALK3", [(0x10, 0x11), (0x12, 0x13), (0x14, 0x15), (0x16, 0x17)]),
            ("SKID", [(0x18, 0x19), (0x1A, 0x1B), (0x1C, 0x1D), (0x1E, 0x1F)]),
            ("JUMP", [(0x20, 0x21), (0x22, 0x23), (0x24, 0x25), (0x26, 0x27)]),
            ("SWIM1", [(0x08, 0x09), (0x28, 0x29), (0x2A, 0x2B), (0x2C, 0x2D)]),
            ("SWIM2", [(0x08, 0x09), (0x0A, 0x0B), (0x0C, 0x30), (0x2C, 0x2D)]),
            ("SWIM3", [(0x08, 0x09), (0x0A, 0x0B), (0x2E, 0x2F), (0x2C, 0x2D)]),
            ("CLIMB1", [(0x08, 0x09), (0x28, 0x29), (0x2A, 0x2B), (0x5C, 0x5D)]),
            ("CLIMB2", [(0x08, 0x09), (0x0A, 0x0B), (0x0C, 0x0D), (0x5E, 0x5F)]),
            ("CROUCH", [(0xFC, 0xFC), (0x08, 0x09), (0x58, 0x59), (0x5A, 0x5A)]),
            ("FIRE", [(0x08, 0x09), (0x28, 0x29), (0x2A, 0x2B), (0x0E, 0x0F)])):
        big.add(label, frame16x32(chr_, [(s(l), s(r)) for l, r in rows]), SPRITE_GRAYS)
    big.write("assets/sprites")

    # ---- Items and effects
    items = Asset("ItemTiles", "Items and effects. 16x16 frames are TL, BL, TR, BR; the coin is 8x16 (top, bottom).")
    coin = []
    for i in (0x60, 0x61, 0x62, 0x63):  # spin: front, turning, edge, turning back
        coin += [t(i), vflip(t(i))]
    items.add("COIN", coin, SPRITE_GRAYS, "4 frames x (top, bottom)")
    items.add("MUSHROOM", frame16(chr_, s(0x76), s(0x77), s(0x78), s(0x79)), SPRITE_GRAYS, "also the 1-up mushroom")
    items.add("FLOWER", frame16(chr_, s(0xD6), s(0xD6), s(0xD9), s(0xD9)), SPRITE_GRAYS)
    items.add("STAR", frame16(chr_, s(0x8D), s(0x8D), s(0xE4), s(0xE4)), SPRITE_GRAYS)
    items.add("BRICK_PIECE", [t(0x84)], SPRITE_GRAYS, "8x8, spun by flipping")
    # Floating scores are two small-digit tiles: "20" + "0" = 200, "1U" + "P" = 1-UP
    items.add("SCORE", [t(i) for i in (0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFD, 0xFE, 0x50)], TEXT_GRAYS,
              '"10" "20" "40" "50" "80" "0" "1U" "P" "00"')
    items.add("FIREBALL", [t(0x64)], SPRITE_GRAYS, "8x8, spun by flipping")
    items.add("EXPLOSION_SMALL", mirror4(0x68), SPRITE_GRAYS, "fireball hit / firework, 16x16")
    items.add("EXPLOSION_MEDIUM", mirror4(0x67), SPRITE_GRAYS)
    items.add("EXPLOSION_LARGE", mirror4(0x66), SPRITE_GRAYS)
    items.add("FLAG", [t(0x7E), vflip(t(0x7E)), t(0x7F), vflip(t(0x7F))], SPRITE_GRAYS, "flagpole flag, 16x16")
    items.add("VINE", [t(0xE0), t(0xE1)], SPRITE_GRAYS, "8x8 leaves, 8x8 stem")
    items.add("PLATFORM", [t(0x5B)], SPRITE_GRAYS, "8x8 lift / balance platform segment")
    items.add("SPRING1", [t(0xF2), hflip(t(0xF2)), t(0xF3), hflip(t(0xF3)), t(0xF2), hflip(t(0xF2))], SPRITE_GRAYS,
              "jumpspring, 16x24 row by row")
    items.add("SPRING2", [t(0xF1), hflip(t(0xF1)), t(0xF1), hflip(t(0xF1)), t(0xFC), t(0xFC)], SPRITE_GRAYS)
    items.add("SPRING3", [t(0xF0), hflip(t(0xF0)), t(0xFC), t(0xFC), t(0xFC), t(0xFC)], SPRITE_GRAYS)
    items.write("assets/sprites")

    # ---- Enemies (EnemyGraphicsTable). 16x16 frames are TL, BL, TR, BR;
    # 16x24 frames are 6 tiles row by row. A repeated left/right tile is mirrored.
    enemies = Asset("EnemyTiles", "Enemies. 16x16 frames: TL, BL, TR, BR. 16x24 frames: 6 tiles row by row (TL, TR, ...). "
                                  "Bowser is 32x24: a FRONT and a REAR 16x24 half side by side.")

    def enemy(label, spec, comment=""):
        ids = [int(x, 16) for x in spec.split()]
        if ids[0] == 0xFC and ids[1] == 0xFC:  # 16x16: only the bottom two rows
            enemies.add(label, frame16(chr_, s(ids[2]), s(ids[3]), s(ids[4]), s(ids[5])), SPRITE_GRAYS, comment or "16x16")
        else:
            tiles = []
            for r in range(3):
                left, right = ids[r * 2], ids[r * 2 + 1]
                tiles += [t(left), hflip(t(left)) if left == right else t(right)]
            enemies.add(label, tiles, SPRITE_GRAYS, comment or "16x24")

    enemy("GOOMBA", "fc fc 70 71 72 73", "16x16, walks by flipping")
    enemy("GOOMBA_FLAT", "fc fc fc fc ef ef", "16x16, stomped")
    enemy("KOOPA1", "fc a5 a6 a7 a8 a9")
    enemy("KOOPA2", "fc a0 a1 a2 a3 a4")
    enemy("PARATROOPA1", "69 a5 6a a7 a8 a9")
    enemy("PARATROOPA2", "6b a0 6c a2 a3 a4")
    enemy("SHELL1", "fc fc 6e 6e 6f 6f", "16x16, upside down (kicked); flip vertically for right side up")
    enemy("SHELL2", "fc fc 6d 6d 6f 6f", "16x16, legs out")
    enemy("BUZZY1", "fc fc aa ab ac ad")
    enemy("BUZZY2", "fc fc ae af b0 b1")
    enemy("BUZZY_SHELL", "fc fc f4 f4 f5 f5")
    enemy("SPINY1", "fc fc 96 97 98 99")
    enemy("SPINY2", "fc fc 9a 9b 9c 9d")
    enemies.add("SPINY_EGG1", mirror4(0x8E), SPRITE_GRAYS, "16x16")
    enemies.add("SPINY_EGG2", mirror4(0x94), SPRITE_GRAYS, "16x16")
    enemy("CHEEP1", "fc fc b2 b3 b4 b5")
    enemy("CHEEP2", "fc fc b6 b3 b7 b5")
    enemy("BLOOBER1", "fc fc dc dc df df")
    enemy("BLOOBER2", "dc dc dd dd de de")
    enemy("LAKITU1", "b9 b8 bb ba bc bc", "16x24, in cloud")
    enemy("LAKITU2", "fc fc bd bd bc bc", "16x16, ducking into cloud")
    enemy("HAMMER_BRO1", "7d 7c d1 8c d3 d2")
    enemy("HAMMER_BRO2", "7d 7c 89 88 8b 8a")
    enemy("HAMMER_BRO3", "d5 d4 e3 e2 d3 d2")
    enemy("HAMMER_BRO4", "d5 d4 e3 e2 8b 8a")
    enemy("PIRANHA1", "e5 e5 e6 e6 eb eb")
    enemy("PIRANHA2", "ec ec ed ed ee ee")
    enemy("PODOBOO", "fc fc d0 d0 d7 d7")
    enemy("BULLET_BILL", "fc fc e8 e7 ea e9")
    enemy("BOWSER_FRONT1", "bf be c1 c0 c2 fc")
    enemy("BOWSER_REAR1", "c4 c3 c6 c5 c8 c7")
    enemy("BOWSER_FRONT2", "bf be ca c9 c2 fc")
    enemy("BOWSER_REAR2", "c4 c3 c6 c5 cc cb")
    enemies.add("BOWSER_FLAME", [t(0x51), t(0x52), t(0x53)], SPRITE_GRAYS, "24x8, left to right")
    enemies.write("assets/sprites")

    # ---- Toad and the Princess
    characters = Asset("CharacterTiles", "Toad and the Princess. 16x24 frames, 6 tiles row by row (TL, TR, ...).")
    for label, spec in (("TOAD", "cd cd ce ce cf cf"), ("PRINCESS", "7a 7b da db d8 d8")):
        ids = [int(x, 16) for x in spec.split()]
        tiles = []
        for r in range(3):
            left, right = ids[r * 2], ids[r * 2 + 1]
            tiles += [t(left), hflip(t(left)) if left == right else t(right)]
        characters.add(label, tiles, SPRITE_GRAYS)
    characters.write("assets/sprites")

    # ---- Font: SMB's own letters, digits and HUD symbols
    chars = " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-x!@"
    nes_index = {' ': 0x24, '-': 0x28, 'x': 0x29, '!': 0x2B, '@': 0x2E}
    for i, ch in enumerate("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"):
        nes_index[ch] = i
    font = Asset("FontTiles", "SMB font, one tile per character in FONT_CHARS ('x' is the times sign, '@' the coin).")
    font.add("FIRST", [chr_.tile(b(nes_index[c])) for c in chars[:-1]], TEXT_GRAYS)
    font.tiles.append((to_gb(chr_.tile(b(nes_index['@'])), SPRITE_GRAYS), "coin icon"))
    font.defines = []
    font.write("assets/tiles", extra_h='// Character for each tile, in order\n#define FONT_CHARS "%s"' % chars)

    # ---- Scenery: every 16x16 background block the game can draw, from its metatile tables
    # Grays per NES palette group
    scenery_grays = [
        BACKGROUND_GRAYS,           # 0: scenery, pipes, trees
        BACKGROUND_GRAYS,           # 1: ground, bricks, castle
        {0: 0, 1: 0, 2: 1, 3: 3},   # 2: clouds, water (white cloud on the white sky)
        BACKGROUND_GRAYS,           # 3: ? blocks, coins, axe
    ]
    write_scenery(chr_, scenery_grays)

    # ---- Everything the named sheets above don't cover, so every tile is somewhere
    leftover_spr = [i for i in range(256) if s(i) not in chr_.used]
    leftover_bg = [i for i in range(256) if b(i) not in chr_.used]
    misc = Asset("MiscSpriteTiles", "Sprite tiles not used by any named sheet, in NES tile order. "
                                    "Each tile's comment gives its NES sprite tile number.")
    misc.defines.append(("MISCSPRITETILES_FIRST", 0, ""))
    for i in leftover_spr:
        misc.tiles.append((to_gb(chr_.tile(s(i)), SPRITE_GRAYS), "nes spr %02X" % i))
    misc.write("assets/sprites")
    misc_bg = Asset("MiscBackgroundTiles", "Background tiles not used by any named sheet (NES title logo pieces, "
                                           "unused tiles), in NES tile order. Each comment gives the NES tile number.")
    misc_bg.defines.append(("MISCBACKGROUNDTILES_FIRST", 0, ""))
    for i in leftover_bg:
        misc_bg.tiles.append((to_gb(chr_.tile(b(i)), BACKGROUND_GRAYS), "nes bg %02X" % i))
    misc_bg.write("assets/tiles")

    render_references()


# SMB's metatile tables (MetatileGraphics_Low/High) in PRG: 4 palette groups,
# 4 tile numbers per metatile in TL, BL, TR, BR order. Names follow the disassembly.
METATILE_TABLE = 0x8B08
METATILE_NAMES = [
    ["BLANK", "BLACK", "BUSH_LEFT", "BUSH_MIDDLE", "BUSH_RIGHT", "HILL_LEFT", "HILL_LEFT_BOTTOM",
     "HILL_TOP", "HILL_RIGHT", "HILL_RIGHT_BOTTOM", "HILL_BOTTOM", "BRIDGE_RAIL", "CHAIN",
     "TALL_TREE_TOP", "SHORT_TREE", "TALL_TREE_BOTTOM", "PIPE_TOP_LEFT", "PIPE_TOP_RIGHT",
     "DECOR_PIPE_TOP_LEFT", "DECOR_PIPE_TOP_RIGHT", "PIPE_LEFT", "PIPE_RIGHT", "TREE_LEDGE_LEFT",
     "TREE_LEDGE_MIDDLE", "TREE_LEDGE_RIGHT", "MUSHROOM_LEFT", "MUSHROOM_MIDDLE", "MUSHROOM_RIGHT",
     "SIDE_PIPE_END_TOP", "SIDE_PIPE_TOP", "SIDE_PIPE_JOINT_TOP", "SIDE_PIPE_END_BOTTOM",
     "SIDE_PIPE_BOTTOM", "SIDE_PIPE_JOINT_BOTTOM", "SEAPLANT", "BLANK_HIT", "FLAGPOLE_BALL",
     "FLAGPOLE", "BLANK_VINE"],
    ["ROPE_VERTICAL", "ROPE_HORIZONTAL", "PULLEY_LEFT", "PULLEY_RIGHT", "BLANK_ROPE", "CASTLE_TOP",
     "CASTLE_WINDOW_LEFT", "CASTLE_WALL", "CASTLE_WINDOW_RIGHT", "CASTLE_TOP_BRICK", "CASTLE_DOOR_TOP",
     "CASTLE_DOOR", "LEDGE_STUMP", "FENCE", "TREE_TRUNK", "MUSHROOM_STUMP_TOP", "MUSHROOM_STUMP",
     "BRICK_LINE", "BRICK", "BRICK_UNUSED", "ROCK", "BRICK_LINE_POWERUP", "BRICK_LINE_VINE",
     "BRICK_LINE_STAR", "BRICK_LINE_COINS", "BRICK_LINE_1UP", "BRICK_POWERUP", "BRICK_VINE",
     "BRICK_STAR", "BRICK_COINS", "BRICK_1UP", "HIDDEN_COIN", "HIDDEN_1UP", "STAIR_BLOCK",
     "WHITE_WALL", "BRIDGE", "CANNON_BARREL", "CANNON_TOP", "CANNON_BOTTOM", "BLANK_SPRING",
     "HALF_BRICK_SPRING", "WATER_ROCK", "HALF_BRICK", "WATER_PIPE_TOP", "WATER_PIPE_BOTTOM",
     "FLAG_BALL"],
    ["CLOUD_LEFT", "CLOUD_MIDDLE", "CLOUD_RIGHT", "CLOUD_BOTTOM_LEFT", "CLOUD_BOTTOM_MIDDLE",
     "CLOUD_BOTTOM_RIGHT", "WATER_TOP", "WATER", "CLOUD_GROUND", "BOWSER_BRIDGE"],
    ["QUESTION_COIN", "QUESTION_POWERUP", "COIN", "WATER_COIN", "USED_BLOCK", "AXE"],
]


def write_scenery(chr_, grays):
    """SceneryTiles: unique tiles plus a table of 4 tile indexes per metatile"""
    prg = chr_.prg
    base = METATILE_TABLE - 0x8000
    pointers = [prg[base + k] | (prg[base + 4 + k] << 8) for k in range(4)]
    unique = {}      # gb bytes -> index
    tiles = []       # (bytes, comment)
    table = []       # (name, [TL, TR, BL, BR] tile indexes)
    for group, names in enumerate(METATILE_NAMES):
        for m, name in enumerate(names):
            o = pointers[group] - 0x8000 + m * 4
            tl, bl, tr, br = prg[o:o + 4]
            idx = []
            for nes in (tl, tr, bl, br):
                data = tuple(to_gb(chr_.tile(BG + nes), grays[group]))
                if data not in unique:
                    unique[data] = len(tiles)
                    tiles.append((list(data), "nes bg %02X (palette %d)" % (nes, group)))
                idx.append(unique[data])
            table.append((name, idx))

    h = ["/*", " SCENERYTILES.H", "",
         " Every 16x16 background block (metatile) Super Mario Bros. can draw: overworld,",
         " underground, castle, water and sky scenery, blocks, pipes, bridges, the axe...",
         " SceneryTiles holds the unique 8x8 tiles; SceneryMetatiles holds 4 tile indexes",
         " per block (TL, TR, BL, BR) and SCENERY_<NAME> is a block's number in it.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/",
         "#ifndef __SceneryTiles_h_INCLUDE", "#define __SceneryTiles_h_INCLUDE", "",
         "#include <gbdk/platform.h>", "",
         "#define SceneryTilesCount %d" % len(tiles),
         "#define SceneryMetatileCount %d" % len(table), ""]
    for n, (name, idx) in enumerate(table):
        h.append("#define SCENERY_%-26s %3d" % (name, n))
    h += ["", "// In a switchable ROM bank: switch to BANK(SceneryTiles) before reading either array",
          "BANKREF_EXTERN(SceneryTiles)", "extern const unsigned char SceneryTiles[];",
          "extern const unsigned char SceneryMetatiles[];", "", "#endif", ""]
    c = ["/*", " SCENERYTILES.C", "", " See SceneryTiles.h.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/", "",
         "#pragma bank %d" % GRAPHICS_BANK, "", "#include <gbdk/platform.h>", "", "BANKREF(SceneryTiles)", "",
         "const unsigned char SceneryTiles[] =", "{"]
    for data, comment in tiles:
        c.append("  " + ",".join("0x%02X" % v for v in data) + ", // " + comment)
    c += ["};", "", "// 4 SceneryTiles indexes per block: TL, TR, BL, BR",
          "const unsigned char SceneryMetatiles[] =", "{"]
    for name, idx in table:
        c.append("  " + ",".join("%3d" % v for v in idx) + ", // " + name)
    c += ["};", ""]
    out = os.path.join(ROOT, "assets", "tiles", "SceneryTiles")
    open(out + ".h", "w", newline="\n").write("\n".join(h))
    open(out + ".c", "w", newline="\n").write("\n".join(c))
    print("wrote assets/tiles/SceneryTiles.c/.h (%d tiles, %d blocks)" % (len(tiles), len(table)))


if __name__ == "__main__":
    main()
