"""Extract Super Mario Bros. (NES) graphics into GBDK assets.

Usage:  python tools/nes2gb.py path/to/SuperMarioBros.nes

The ROM itself is never copied into the project; only the converted tiles are
written, to assets/sprites and assets/tiles. Rerun after changing anything here.

It also writes references/<Sheet>.png: every tile sheet in assets/, each
tile shown in Game Boy grays with its index in the sheet below it.

NES and Game Boy tiles are both 8x8 with 2 bits per pixel, but the NES stores
all 8 rows of bitplane 0 followed by bitplane 1, while the Game Boy interleaves
the two planes row by row. The NES also colors each tile through a palette, so
every asset below says how its 4 NES color indexes map to the Game Boy's
4 grays (0 = white / transparent on sprites, 1 = light, 2 = dark, 3 = black).

Tile numbers and layouts come from the game's own tables (see the SMB
disassembly: PlayerGraphicsTable, EnemyGraphicsTable, PowerUpGfxTable,
JumpingCoinTiles, FloateyNumTileData, and the metatile graphics tables).
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Every sheet lives in this ROM bank; code gets it with BANK(<sheet name>)
GRAPHICS_BANK = 2
PRG_SIZE = 32768
CHR_SIZE = 8192
SPR = 0x000  # sprite pattern table
BG = 0x100   # background pattern table

# NES color index -> Game Boy gray
SPRITE_GRAYS = {0: 0, 1: 2, 2: 1, 3: 3}  # red -> dark, skin/tan -> light, brown -> black
ONE_UP_GRAYS = {0: 0, 1: 1, 2: 2, 3: 3}   # the mushroom with its two colors' shades swapped
TEXT_GRAYS = {0: 0, 1: 3, 2: 3, 3: 3}    # any ink -> black on the white sky
BACKGROUND_GRAYS = {0: 0, 1: 1, 2: 2, 3: 3}  # sky -> white, then light to dark as on the NES


def load_rom(path):
    """(CHR tile data, PRG program data)"""
    data = open(path, 'rb').read()
    if data[:4] != b'NES\x1a' or data[4] != 2 or data[5] != 1:
        sys.exit("%s doesn't look like the Super Mario Bros. NES ROM (NROM, 32K PRG + 8K CHR)" % path)
    start = 16 + PRG_SIZE
    return data[start:start + CHR_SIZE], data[16:start]


class Chr:
    def __init__(self, data, prg):
        self.data = data
        self.prg = prg
        self.used = set()  # tiles the named sheets use, so leftovers go in the Misc sheets

    def tile(self, index):
        """8x8 list of NES color indexes"""
        self.used.add(index)
        b = self.data[index * 16:index * 16 + 16]
        return [[((b[y] >> (7 - x)) & 1) | (((b[y + 8] >> (7 - x)) & 1) << 1) for x in range(8)] for y in range(8)]


def hflip(t):
    return [row[::-1] for row in t]


def vflip(t):
    return t[::-1]


def to_gb(t, grays):
    """Game Boy 2bpp bytes (low plane, high plane per row)"""
    out = []
    for row in t:
        lo = hi = 0
        for x, v in enumerate(row):
            g = grays[v]
            if g & 1:
                lo |= 0x80 >> x
            if g & 2:
                hi |= 0x80 >> x
        out += [lo, hi]
    return out


class Asset:
    """Collects tiles plus a named index for each frame, then writes .c/.h"""

    def __init__(self, name, description):
        self.name = name
        self.description = description
        self.tiles = []     # (bytes, comment)
        self.defines = []   # (name, value, comment)

    def add(self, label, tiles, grays, comment=""):
        self.defines.append(("%s_%s" % (self.name.upper(), label), len(self.tiles), comment))
        for i, t in enumerate(tiles):
            self.tiles.append((to_gb(t, grays), "%s %d" % (label.lower(), i)))

    def write(self, folder, extra_h=""):
        guard = "__%s_h_INCLUDE" % self.name
        h = ["/*", " %s.H" % self.name.upper(), "", " " + self.description, "",
             " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
             " Do not edit; change the script and rerun it.", "*/",
             "#ifndef %s" % guard, "#define %s" % guard, "",
             "#include <gbdk/platform.h>", "",
             "#define %sCount %d" % (self.name, len(self.tiles)), ""]
        for name, value, comment in self.defines:
            h.append("#define %-28s %3d%s" % (name, value, ("  // " + comment) if comment else ""))
        h += ["", "// In a switchable ROM bank: switch to BANK(%s) before reading it" % self.name,
              "BANKREF_EXTERN(%s)" % self.name, "extern const unsigned char %s[];" % self.name]
        if extra_h:
            h += ["", extra_h]
        h += ["", "#endif", ""]
        c = ["/*", " %s.C" % self.name.upper(), "", " " + self.description, "",
             " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
             " Do not edit; change the script and rerun it.", "*/", "",
             "#pragma bank %d" % GRAPHICS_BANK, "", "#include <gbdk/platform.h>", "",
             "BANKREF(%s)" % self.name, "",
             "const unsigned char %s[] =" % self.name, "{"]
        for data, comment in self.tiles:
            c.append("  " + ",".join("0x%02X" % b for b in data) + ", // " + comment)
        c += ["};", ""]
        base = os.path.join(ROOT, folder, self.name)
        open(base + ".h", "w", newline="\n").write("\n".join(h))
        open(base + ".c", "w", newline="\n").write("\n".join(c))
        print("wrote %s.c/.h (%d tiles)" % (os.path.join(folder, self.name), len(self.tiles)))


def frame16(chr_, tl, tr, bl, br, mirror_right=False):
    """16x16 frame in metasprite order: TL, BL, TR, BR (column by column).
    SMB draws a repeated left/right tile mirrored on the right."""
    t_tr = hflip(chr_.tile(tl)) if (mirror_right or tl == tr) else chr_.tile(tr)
    t_br = hflip(chr_.tile(bl)) if (mirror_right or bl == br) else chr_.tile(br)
    return [chr_.tile(tl), chr_.tile(bl), t_tr, t_br]


def frame16x32(chr_, rows):
    """16x32 frame from 4 (left, right) rows, returned row by row: TL, TR, ..."""
    out = []
    for left, right in rows:
        out.append(chr_.tile(left))
        out.append(hflip(chr_.tile(left)) if left == right else chr_.tile(right))
    return out


def render_references():
    """references/<Sheet>.png for every tile sheet in assets/: each tile at 4x
    in Game Boy grays, with its index in the sheet written below it"""
    import glob
    import re
    from PIL import Image, ImageDraw

    out_dir = os.path.join(ROOT, "references")
    os.makedirs(out_dir, exist_ok=True)
    grays = [(255, 255, 255), (170, 170, 170), (85, 85, 85), (0, 0, 0)]
    scale, columns = 4, 16
    cell_w, cell_h = 8 * scale + 8, 8 * scale + 14

    for path in sorted(glob.glob(os.path.join(ROOT, "assets", "*", "*.c"))):
        text = open(path).read()
        match = re.search(r"const unsigned char (\w*Tiles)\[\] =\s*\{(.*?)\};", text, re.S)
        if not match:
            continue  # not a tile sheet (maps, metasprites)
        name = match.group(1)
        body = re.sub(r"//[^\n]*", "", match.group(2))
        data = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body)]
        count = len(data) // 16
        rows = (count + columns - 1) // columns
        sheet = Image.new("RGB", (columns * cell_w + 4, rows * cell_h + 4), (200, 220, 255))
        draw = ImageDraw.Draw(sheet)
        for i in range(count):
            x0 = 4 + (i % columns) * cell_w
            y0 = 4 + (i // columns) * cell_h
            tile = Image.new("RGB", (8, 8))
            for y in range(8):
                lo, hi = data[i * 16 + y * 2], data[i * 16 + y * 2 + 1]
                for x in range(8):
                    tile.putpixel((x, y), grays[((lo >> (7 - x)) & 1) | (((hi >> (7 - x)) & 1) << 1)])
            sheet.paste(tile.resize((8 * scale, 8 * scale), Image.NEAREST), (x0, y0))
            label = str(i)
            draw.text((x0 + (8 * scale - 6 * len(label)) // 2, y0 + 8 * scale + 1), label, fill=(0, 0, 0))
        sheet.save(os.path.join(out_dir, name + ".png"))
    print("wrote references/*.png")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        sys.exit(__doc__)
    chr_ = Chr(*load_rom(args[0]))
    s = lambda i: SPR + i
    b = lambda i: BG + i
    t = lambda i: chr_.tile(s(i))
    mirror4 = lambda i: [t(i), vflip(t(i)), hflip(t(i)), hflip(vflip(t(i)))]  # TL, BL, TR, BR

    # ---- Small Mario: 16x16 frames, same order the existing metasprites use (PlayerGraphicsTable)
    mario = Asset("MarioTiles", "Small Mario. 4 tiles per 16x16 frame: TL, BL, TR, BR.")
    mario.add("STAND", frame16(chr_, s(0x3A), s(0x37), s(0x4F), s(0x4F)), SPRITE_GRAYS)
    mario.add("WALK1", frame16(chr_, s(0x32), s(0x33), s(0x34), s(0x35)), SPRITE_GRAYS)
    mario.add("WALK2", frame16(chr_, s(0x36), s(0x37), s(0x38), s(0x39)), SPRITE_GRAYS)
    mario.add("WALK3", frame16(chr_, s(0x3A), s(0x37), s(0x3B), s(0x3C)), SPRITE_GRAYS)
    mario.add("JUMP", frame16(chr_, s(0x32), s(0x41), s(0x42), s(0x43)), SPRITE_GRAYS)
    mario.add("SKID", frame16(chr_, s(0x3D), s(0x3E), s(0x3F), s(0x40)), SPRITE_GRAYS)
    mario.add("DEAD", frame16(chr_, s(0x9E), s(0x9E), s(0x9F), s(0x9F)), SPRITE_GRAYS)
    mario.add("SWIM1", frame16(chr_, s(0x32), s(0x33), s(0x44), s(0x45)), SPRITE_GRAYS)
    mario.add("SWIM2", frame16(chr_, s(0x32), s(0x33), s(0x44), s(0x47)), SPRITE_GRAYS)
    mario.add("SWIM3", frame16(chr_, s(0x32), s(0x33), s(0x48), s(0x49)), SPRITE_GRAYS)
    mario.add("CLIMB1", frame16(chr_, s(0x32), s(0x33), s(0x90), s(0x91)), SPRITE_GRAYS)
    mario.add("CLIMB2", frame16(chr_, s(0x3A), s(0x37), s(0x92), s(0x93)), SPRITE_GRAYS)
    mario.write("assets/sprites")

    # ---- Big Mario (also Fire Mario: same tiles, different NES palette)
    big = Asset("BigMarioTiles", "Big / Fire Mario. 8 tiles per 16x32 frame, row by row: TL, TR, then down.")
    for label, rows in (
            ("STAND", [(0x00, 0x01), (0x4C, 0x4D), (0x4A, 0x4A), (0x4B, 0x4B)]),
            ("WALK1", [(0x00, 0x01), (0x02, 0x03), (0x04, 0x05), (0x06, 0x07)]),
            ("WALK2", [(0x08, 0x09), (0x0A, 0x0B), (0x0C, 0x0D), (0x0E, 0x0F)]),
            ("WALK3", [(0x10, 0x11), (0x12, 0x13), (0x14, 0x15), (0x16, 0x17)]),
            ("SKID", [(0x18, 0x19), (0x1A, 0x1B), (0x1C, 0x1D), (0x1E, 0x1F)]),
            ("JUMP", [(0x20, 0x21), (0x22, 0x23), (0x24, 0x25), (0x26, 0x27)]),
            ("SWIM1", [(0x08, 0x09), (0x28, 0x29), (0x2A, 0x2B), (0x2C, 0x2D)]),
            ("SWIM2", [(0x08, 0x09), (0x0A, 0x0B), (0x0C, 0x30), (0x2C, 0x2D)]),
            ("SWIM3", [(0x08, 0x09), (0x0A, 0x0B), (0x2E, 0x2F), (0x2C, 0x2D)]),
            ("CLIMB1", [(0x08, 0x09), (0x28, 0x29), (0x2A, 0x2B), (0x5C, 0x5D)]),
            ("CLIMB2", [(0x08, 0x09), (0x0A, 0x0B), (0x0C, 0x0D), (0x5E, 0x5F)]),
            ("CROUCH", [(0xFC, 0xFC), (0x08, 0x09), (0x58, 0x59), (0x5A, 0x5A)]),
            ("FIRE", [(0x08, 0x09), (0x28, 0x29), (0x2A, 0x2B), (0x0E, 0x0F)])):
        big.add(label, frame16x32(chr_, [(s(l), s(r)) for l, r in rows]), SPRITE_GRAYS)
    big.write("assets/sprites")

    # ---- Items and effects
    items = Asset("ItemTiles", "Items and effects. 16x16 frames are TL, BL, TR, BR; the coin is 8x16 (top, bottom).")
    coin = []
    for i in (0x60, 0x61, 0x62, 0x63):  # spin: front, turning, edge, turning back
        coin += [t(i), vflip(t(i))]
    items.add("COIN", coin, SPRITE_GRAYS, "4 frames x (top, bottom)")
    items.add("MUSHROOM", frame16(chr_, s(0x76), s(0x77), s(0x78), s(0x79)), SPRITE_GRAYS, "also the 1-up mushroom")
    items.add("FLOWER", frame16(chr_, s(0xD6), s(0xD6), s(0xD9), s(0xD9)), SPRITE_GRAYS)
    items.add("STAR", frame16(chr_, s(0x8D), s(0x8D), s(0xE4), s(0xE4)), SPRITE_GRAYS)
    items.add("BRICK_PIECE", [t(0x84)], SPRITE_GRAYS, "8x8, spun by flipping")
    # Floating scores are two small-digit tiles: "20" + "0" = 200, "1U" + "P" = 1-UP
    items.add("SCORE", [t(i) for i in (0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFD, 0xFE, 0x50)], TEXT_GRAYS,
              '"10" "20" "40" "50" "80" "0" "1U" "P" "00"')
    items.add("FIREBALL", [t(0x64)], SPRITE_GRAYS, "8x8, spun by flipping")
    items.add("EXPLOSION_SMALL", mirror4(0x68), SPRITE_GRAYS, "fireball hit / firework, 16x16")
    items.add("EXPLOSION_MEDIUM", mirror4(0x67), SPRITE_GRAYS)
    items.add("EXPLOSION_LARGE", mirror4(0x66), SPRITE_GRAYS)
    # SMB's flag is 3 sprites (FlagpoleGfxHandler): the triangle at the top left, the
    # emblem beside it at the pole, and the triangle again under the emblem
    blank = [[0] * 8 for _ in range(8)]
    items.add("FLAG", [t(0x7E), blank, t(0x7F), t(0x7E)], SPRITE_GRAYS, "flagpole flag, 16x16")
    items.add("VINE", [t(0xE0), t(0xE1)], SPRITE_GRAYS, "8x8 leaves, 8x8 stem")
    items.add("PLATFORM", [t(0x5B)], SPRITE_GRAYS, "8x8 lift / balance platform segment")
    items.add("SPRING1", [t(0xF2), hflip(t(0xF2)), t(0xF3), hflip(t(0xF3)), t(0xF2), hflip(t(0xF2))], SPRITE_GRAYS,
              "jumpspring, 16x24 row by row")
    items.add("SPRING2", [t(0xF1), hflip(t(0xF1)), t(0xF1), hflip(t(0xF1)), t(0xFC), t(0xFC)], SPRITE_GRAYS)
    items.add("SPRING3", [t(0xF0), hflip(t(0xF0)), t(0xFC), t(0xFC), t(0xFC), t(0xFC)], SPRITE_GRAYS)
    items.add("CASTLE_FLAG", [t(0x54), t(0x56), t(0x55), t(0x57)], SPRITE_GRAYS, "star flag raised over the castle, 16x16")
    # SMB draws the 1-up mushroom with a green palette; here its shades are swapped instead
    items.add("ONE_UP", frame16(chr_, s(0x76), s(0x77), s(0x78), s(0x79)), ONE_UP_GRAYS, "1-up mushroom, 16x16")
    items.write("assets/sprites")

    # ---- Enemies (EnemyGraphicsTable). 16x16 frames are TL, BL, TR, BR;
    # 16x24 frames are 6 tiles row by row. A repeated left/right tile is mirrored.
    enemies = Asset("EnemyTiles", "Enemies. 16x16 frames: TL, BL, TR, BR. 16x24 frames: 6 tiles row by row (TL, TR, ...). "
                                  "Bowser is 32x24: a FRONT and a REAR 16x24 half side by side.")

    def enemy(label, spec, comment=""):
        ids = [int(x, 16) for x in spec.split()]
        if ids[0] == 0xFC and ids[1] == 0xFC:  # 16x16: only the bottom two rows
            enemies.add(label, frame16(chr_, s(ids[2]), s(ids[3]), s(ids[4]), s(ids[5])), SPRITE_GRAYS, comment or "16x16")
        else:
            tiles = []
            for r in range(3):
                left, right = ids[r * 2], ids[r * 2 + 1]
                tiles += [t(left), hflip(t(left)) if left == right else t(right)]
            enemies.add(label, tiles, SPRITE_GRAYS, comment or "16x24")

    enemy("GOOMBA", "fc fc 70 71 72 73", "16x16, walks by flipping")
    enemy("GOOMBA_FLAT", "fc fc fc fc ef ef", "16x16, stomped")
    enemy("KOOPA1", "fc a5 a6 a7 a8 a9")
    enemy("KOOPA2", "fc a0 a1 a2 a3 a4")
    enemy("PARATROOPA1", "69 a5 6a a7 a8 a9")
    enemy("PARATROOPA2", "6b a0 6c a2 a3 a4")
    enemy("SHELL1", "fc fc 6e 6e 6f 6f", "16x16, upside down (kicked); flip vertically for right side up")
    enemy("SHELL2", "fc fc 6d 6d 6f 6f", "16x16, legs out")
    enemy("BUZZY1", "fc fc aa ab ac ad")
    enemy("BUZZY2", "fc fc ae af b0 b1")
    enemy("BUZZY_SHELL", "fc fc f4 f4 f5 f5")
    enemy("SPINY1", "fc fc 96 97 98 99")
    enemy("SPINY2", "fc fc 9a 9b 9c 9d")
    enemies.add("SPINY_EGG1", mirror4(0x8E), SPRITE_GRAYS, "16x16")
    enemies.add("SPINY_EGG2", mirror4(0x94), SPRITE_GRAYS, "16x16")
    enemy("CHEEP1", "fc fc b2 b3 b4 b5")
    enemy("CHEEP2", "fc fc b6 b3 b7 b5")
    enemy("BLOOBER1", "fc fc dc dc df df")
    enemy("BLOOBER2", "dc dc dd dd de de")
    enemy("LAKITU1", "b9 b8 bb ba bc bc", "16x24, in cloud")
    enemy("LAKITU2", "fc fc bd bd bc bc", "16x16, ducking into cloud")
    enemy("HAMMER_BRO1", "7d 7c d1 8c d3 d2")
    enemy("HAMMER_BRO2", "7d 7c 89 88 8b 8a")
    enemy("HAMMER_BRO3", "d5 d4 e3 e2 d3 d2")
    enemy("HAMMER_BRO4", "d5 d4 e3 e2 8b 8a")
    enemy("PIRANHA1", "e5 e5 e6 e6 eb eb")
    enemy("PIRANHA2", "ec ec ed ed ee ee")
    enemy("PODOBOO", "fc fc d0 d0 d7 d7")
    enemy("BULLET_BILL", "fc fc e8 e7 ea e9")
    enemy("BOWSER_FRONT1", "bf be c1 c0 c2 fc")
    enemy("BOWSER_REAR1", "c4 c3 c6 c5 c8 c7")
    enemy("BOWSER_FRONT2", "bf be ca c9 c2 fc")
    enemy("BOWSER_REAR2", "c4 c3 c6 c5 cc cb")
    enemies.add("BOWSER_FLAME", [t(0x51), t(0x52), t(0x53)], SPRITE_GRAYS, "24x8, left to right")
    enemies.write("assets/sprites")

    # ---- Toad and the Princess
    characters = Asset("CharacterTiles", "Toad and the Princess. 16x24 frames, 6 tiles row by row (TL, TR, ...).")
    for label, spec in (("TOAD", "cd cd ce ce cf cf"), ("PRINCESS", "7a 7b da db d8 d8")):
        ids = [int(x, 16) for x in spec.split()]
        tiles = []
        for r in range(3):
            left, right = ids[r * 2], ids[r * 2 + 1]
            tiles += [t(left), hflip(t(left)) if left == right else t(right)]
        characters.add(label, tiles, SPRITE_GRAYS)
    characters.write("assets/sprites")

    # ---- Font: SMB's own letters, digits and HUD symbols
    chars = " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-x!@"
    nes_index = {' ': 0x24, '-': 0x28, 'x': 0x29, '!': 0x2B, '@': 0x2E}
    for i, ch in enumerate("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"):
        nes_index[ch] = i
    font = Asset("FontTiles", "SMB font, one tile per character in FONT_CHARS ('x' is the times sign, '@' the coin).")
    font.add("FIRST", [chr_.tile(b(nes_index[c])) for c in chars[:-1]], TEXT_GRAYS)
    font.tiles.append((to_gb(chr_.tile(b(nes_index['@'])), SPRITE_GRAYS), "coin icon"))
    font.defines = []
    font.write("assets/tiles", extra_h='// Character for each tile, in order\n#define FONT_CHARS "%s"' % chars)

    # ---- Scenery: every 16x16 background block the game can draw, from its metatile tables
    # Grays per NES palette group
    scenery_grays = [
        BACKGROUND_GRAYS,           # 0: scenery, pipes, trees
        BACKGROUND_GRAYS,           # 1: ground, bricks, castle
        {0: 0, 1: 0, 2: 1, 3: 3},   # 2: clouds, water (white cloud on the white sky)
        BACKGROUND_GRAYS,           # 3: ? blocks, coins, axe
    ]
    write_scenery(chr_, scenery_grays)

    # ---- Everything the named sheets above don't cover, so every tile is somewhere
    leftover_spr = [i for i in range(256) if s(i) not in chr_.used]
    leftover_bg = [i for i in range(256) if b(i) not in chr_.used]
    misc = Asset("MiscSpriteTiles", "Sprite tiles not used by any named sheet, in NES tile order. "
                                    "Each tile's comment gives its NES sprite tile number.")
    misc.defines.append(("MISCSPRITETILES_FIRST", 0, ""))
    for i in leftover_spr:
        misc.tiles.append((to_gb(chr_.tile(s(i)), SPRITE_GRAYS), "nes spr %02X" % i))
    misc.write("assets/sprites")
    misc_bg = Asset("MiscBackgroundTiles", "Background tiles not used by any named sheet (NES title logo pieces, "
                                           "unused tiles), in NES tile order. Each comment gives the NES tile number.")
    misc_bg.defines.append(("MISCBACKGROUNDTILES_FIRST", 0, ""))
    for i in leftover_bg:
        misc_bg.tiles.append((to_gb(chr_.tile(b(i)), BACKGROUND_GRAYS), "nes bg %02X" % i))
    misc_bg.write("assets/tiles")

    write_levels(chr_.prg)
    write_music(chr_.prg)

    render_references()


# SMB enemy lists: 2 bytes per enemy, [column << 4 | row], [page flag (bit 7),
# hard mode only (bit 6), enemy id (bits 0-5)]. Row $E is a 3-byte pipe-warp
# entry (its second byte still carries the page flag), row $F sets the page
# directly, $FF ends the list. Pages are 16 blocks wide.
ENEMY_LIST_1_1 = 0x9F01  # World 1-1
ENEMY_IDS = {0x06: "GOOMBA", 0x00: "KOOPA", 0x03: "RED_KOOPA",   # green and red Koopa Troopas
             0x26: "LIFT_DOWN", 0x27: "LIFT_UP",                  # 1-2's lifts that keep going round
             0x34: "WARP_ZONE"}                                   # (its text, and the pipes' numbers)
# The game's ENEMY_* numbers (see LevelEnemies.h)
ENEMY_TYPES = ["GOOMBA", "KOOPA", "RED_KOOPA", "PIRANHA", "LIFT_UP", "LIFT_DOWN"]
# Enemy groups ignore the row: they stand on a fixed row and are 24 pixels apart
ENEMY_GROUPS = {0x37: ("GOOMBA", 2, 11), 0x38: ("GOOMBA", 3, 11), 0x39: ("GOOMBA", 2, 7), 0x3A: ("GOOMBA", 3, 7),
                0x3B: ("KOOPA", 2, 11), 0x3C: ("KOOPA", 3, 11), 0x3D: ("KOOPA", 2, 7), 0x3E: ("KOOPA", 3, 7)}


def read_enemy_list(prg, address):
    """[(x pixels, y pixels of the 16x16 body's top, type name)] for normal mode"""
    i = address - 0x8000
    page = 0
    enemies = []
    while prg[i] != 0xFF:
        column, row = prg[i] >> 4, prg[i] & 0x0F
        if row == 0x0E:           # pipe warp
            if prg[i + 1] & 0x80:
                page += 1
            i += 3
            continue
        flags = prg[i + 1]
        i += 2
        if row == 0x0F:           # set page
            page = flags & 0x3F
            continue
        if flags & 0x80:
            page += 1
        if flags & 0x40:          # hard mode (second quest) only
            continue
        x = (page * 16 + column) * 16
        enemy = flags & 0x3F
        if enemy in ENEMY_GROUPS:
            kind, count, group_row = ENEMY_GROUPS[enemy]
            for k in range(count):
                enemies.append((x + k * 24, (group_row + 1) * 16, kind))
        elif enemy in ENEMY_IDS:
            enemies.append((x, (row + 1) * 16, ENEMY_IDS[enemy]))
        else:
            sys.exit("enemy id %02X at x=%d isn't handled yet" % (enemy, x))
    return enemies


# ---- Level (area) data. SMB keeps each area as a 2-byte header and a list of
# 2-byte objects: [column << 4 | row], [page flag (bit 7), kind (bits 6-4),
# length (bits 3-0)]; $FD ends it. Rows 0-11 hold blocks, rows 12-15 special
# objects. The terrain (floor and ceiling pattern) is drawn first, objects over it.
# The decoder handles the objects the areas we use need; anything else stops it.
AREA_DATA_H_OFFSETS, AREA_DATA_LOW, AREA_DATA_HIGH = 0x9D28, 0x9D2C, 0x9D4E
ENEMY_ADDR_H_OFFSETS, ENEMY_DATA_LOW, ENEMY_DATA_HIGH = 0x9CE0, 0x9CE4, 0x9D06
AREA_1_1 = 0x25
# per area type: water, ground, underground, castle
TERRAIN_METATILES = [0x69, 0x54, 0x52, 0x62]
BRICK_METATILES = [0x22, 0x51, 0x52, 0x52]
SOLID_METATILES = [0x69, 0x61, 0x61, 0x62]
COIN_METATILES = [0xC3, 0xC2, 0xC2, 0xC2]
UNDERGROUND_FLOOR = 0x54   # underground terrain turns to ground from row 11 down
# TerrainRenderBits: rows 0-7 in the first byte, rows 8-12 in the second (bit 0 = top)
TERRAIN_BITS = [(0x00, 0x00), (0x00, 0x18), (0x01, 0x18), (0x07, 0x18), (0x0F, 0x18), (0xFF, 0x18),
                (0x01, 0x1F), (0x07, 0x1F), (0x0F, 0x1F), (0x81, 0x1F), (0x01, 0x00), (0x8F, 0x1F),
                (0xF1, 0x1F), (0xF9, 0x18), (0xF1, 0x18), (0xFF, 0x1F)]
# Small objects (kind 0 in rows 0-11) by length: ? blocks, hidden blocks, bricks with items, used block
SMALL_OBJECTS = {0: 0xC1, 1: 0xC0, 2: 0x5F, 3: 0x60, 4: 0x55, 5: 0x56, 6: 0x57, 7: 0x58, 8: 0x59, 0xA: 0xC4}
PLAYER_START_Y = [0x00, 0x20, 0xB0, 0x50, 0x00, 0x00, 0xB0, 0xB0]  # by the header's start position
PLAYER_START_X = 0x28
AREA_ROWS = 13        # SMB's rows 0-12 are our map rows 2-14 (rows 0-1 are under its status bar)
MAP_ROW_OFFSET = 2


def area_type(ptr):
    return (ptr >> 5) & 3


def area_address(prg, ptr, h_offsets, low, high):
    k = prg[h_offsets - 0x8000 + area_type(ptr)] + (ptr & 0x1F)
    return prg[low - 0x8000 + k] | (prg[high - 0x8000 + k] << 8)


def read_warps(prg, ptr):
    """The pipe warps in an area's enemy list: (page it applies from, destination area, world, page there)"""
    i = area_address(prg, ptr, ENEMY_ADDR_H_OFFSETS, ENEMY_DATA_LOW, ENEMY_DATA_HIGH) - 0x8000
    page, warps = 0, []
    while prg[i] != 0xFF:
        row = prg[i] & 0x0F
        if row == 0x0E:
            if prg[i + 1] & 0x80:
                page += 1
            warps.append((page, prg[i + 1] & 0x7F, prg[i + 2] >> 5, prg[i + 2] & 0x1F))
            i += 3
            continue
        if row == 0x0F:
            page = prg[i + 1] & 0x3F
        elif prg[i + 1] & 0x80:
            page += 1
        i += 2
    return warps


BACK_SCENERY_DATA = 0x92FA         # BackSceneryData: 48 columns (3 pages, repeating) per scenery type
BACK_SCENERY_METATILES = 0x938A    # BackSceneryMetatiles: 3 metatiles (top down) per scenery piece
# CastleMetatiles: 5 wide, 11 tall; a castle object draws its top rows down to the floor.
# SMB's second row is $48 $47 $46, which puts the tower's windows at its outer
# edges; here the two are swapped to set them in from the edges, matching the
# hand-made 1-1 castle.
CASTLE_METATILES = [
    [0x00, 0x45, 0x45, 0x45, 0x00], [0x00, 0x46, 0x47, 0x48, 0x00], [0x45, 0x49, 0x49, 0x49, 0x45],
    [0x47, 0x47, 0x4A, 0x47, 0x47], [0x47, 0x47, 0x4B, 0x47, 0x47], [0x49, 0x49, 0x49, 0x49, 0x49],
    [0x47, 0x4A, 0x47, 0x4A, 0x47], [0x47, 0x4B, 0x47, 0x4B, 0x47], [0x47, 0x47, 0x47, 0x47, 0x47],
    [0x4A, 0x47, 0x4A, 0x47, 0x4A], [0x4B, 0x47, 0x4B, 0x47, 0x4B],
]
STAIR_HEIGHTS = [1, 2, 3, 4, 5, 6, 7, 8, 8]   # StaircaseObject: column by column, sitting on the floor
FLOOR_ROW = 10                                # the lowest row objects stand on (the floor is rows 11-12)


class Area:
    """A decoded SMB area: grid[column][row] of SMB metatile numbers, plus the things
    the game needs to know about (pipes and so on)"""
    def __init__(self, header, grid):
        self.header, self.grid = header, grid
        self.pipes = []          # (column, top row, can be entered)
        self.exit_pipe = None    # (column, row of its mouth's top half) of a sideways pipe out
        self.intro_pipe = None   # the same for an intro area's pipe


def decode_area(prg, ptr, width, strict=True):
    """Area for the SMB area `ptr`'s first `width` columns"""
    kind_of_area = area_type(ptr)
    i = area_address(prg, ptr, AREA_DATA_H_OFFSETS, AREA_DATA_LOW, AREA_DATA_HIGH) - 0x8000
    header = (prg[i], prg[i + 1])
    i += 2
    objects, page = [], 0
    while prg[i] != 0xFD:
        b1, b2 = prg[i], prg[i + 1]
        i += 2
        if b2 & 0x80:
            page += 1
        if b1 & 0x0F == 0x0D and not (b2 & 0x40):   # page control: jump to a page
            page = b2 & 0x1F
            continue
        objects.append((page * 16 + (b1 >> 4), b1, b2))
    grid = [[0] * AREA_ROWS for _ in range(width)]
    area = Area(header, grid)
    if header[0] & 0x07 and strict:
        sys.exit("area %02X: foreground scenery %d isn't handled yet" % (ptr, header[0] & 7))

    def put(c, r, m):
        if 0 <= c < width and 0 <= r < AREA_ROWS:
            grid[c][r] = m

    # background scenery (clouds, hills, bushes...), repeating every 3 pages
    scenery = (header[1] >> 4) & 3
    if scenery:
        for c in range(width):
            v = prg[BACK_SCENERY_DATA - 0x8000 + (scenery - 1) * 48 + c % 48]
            if v:
                piece = BACK_SCENERY_METATILES - 0x8000 + ((v & 0x0F) - 1) * 3
                for k in range(3):
                    if prg[piece + k]:
                        put(c, (v >> 4) + k, prg[piece + k])

    # terrain, column by column. A row 14 object changes it from the column after
    # its own: SMB draws each column's terrain before it reads that column's objects.
    terrain = header[1] & 0x0F
    changes = {c + 1: b2 & 0x0F for c, b1, b2 in objects if b1 & 0x0F == 0x0E and not (b2 & 0x40)}
    for c in range(width):
        terrain = changes.get(c, terrain)
        bits = TERRAIN_BITS[terrain][0] | (TERRAIN_BITS[terrain][1] << 8)
        metatile = TERRAIN_METATILES[kind_of_area]
        for r in range(AREA_ROWS):
            if kind_of_area == 2 and r == 11:
                metatile = UNDERGROUND_FLOOR
            if bits & (1 << r):
                grid[c][r] = metatile

    def sideways_pipe(c, length, shaft_top=0):
        """exit/intro pipe: the sideways part at rows length-1..length, joined to a pipe going up"""
        shaft = length - 2
        for k, (top, bottom) in enumerate(((0x1C, 0x1F), (0x1D, 0x20), (0x1E, 0x21), (0x15, 0x15))):
            if k >= 2:
                for r in range(shaft_top, shaft + 1):
                    put(c + k, r, 0x14 if k == 2 else 0x15)
            put(c + k, shaft + 1, top)
            put(c + k, shaft + 2, bottom)
        return (c, shaft + 1)

    for c, b1, b2 in objects:
        if c >= width:
            continue
        row, length, kind = b1 & 0x0F, b2 & 0x0F, (b2 >> 4) & 7
        if row <= 11 and kind == 0 and length in SMALL_OBJECTS:
            m = SMALL_OBJECTS[length]
            if kind_of_area != 1 and 0x55 <= m <= 0x59:
                m += 5   # bricks with items outside ground levels: the plain brick look
            put(c, row, m)
        elif row <= 11 and kind in (2, 3, 4):          # rows of bricks, solid blocks, coins
            m = {2: BRICK_METATILES, 3: SOLID_METATILES, 4: COIN_METATILES}[kind][kind_of_area]
            for k in range(length + 1):
                put(c + k, row, m)
        elif row <= 11 and kind in (5, 6):             # columns of bricks, solid blocks
            m = {5: BRICK_METATILES, 6: SOLID_METATILES}[kind][kind_of_area]
            for k in range(length + 1):
                put(c, row + k, m)
        elif row <= 11 and kind == 7:                  # vertical pipe; bit 3: it can be entered
            enter = bool(b2 & 0x08)
            put(c, row, 0x10 if enter else 0x12)
            put(c + 1, row, 0x11 if enter else 0x13)
            for k in range(1, (b2 & 0x07) + 1):
                put(c, row + k, 0x14)
                put(c + 1, row + k, 0x15)
            area.pipes.append((c, row, enter))
        elif row == 0x0C and kind == 0:                # a pit: rows 8 down to the bottom, cleared
            for k in range(length + 1):
                for r in range(8, AREA_ROWS):
                    put(c + k, r, 0)
        elif row == 0x0C and kind in (6, 7):           # a row of ? blocks (with coins), high or low
            for k in range(length + 1):
                put(c + k, 3 if kind == 6 else 7, 0xC0)
        elif row == 0x0F and kind == 2:                # castle: its top rows, down to the floor
            for r in range(length, FLOOR_ROW + 1):
                for k in range(5):
                    if CASTLE_METATILES[r - length][k]:
                        put(c + k, r, CASTLE_METATILES[r - length][k])
        elif row == 0x0F and kind == 3:                # staircase going up to the right
            for k in range(length + 1):
                for r in range(FLOOR_ROW + 1 - STAIR_HEIGHTS[k], FLOOR_ROW + 1):
                    put(c + k, r, SOLID_METATILES[kind_of_area])
        elif row == 0x0F and kind == 4:                # exit pipe: sideways, joined to a pipe going up
            area.exit_pipe = sideways_pipe(c, length)
        elif row == 0x0D and b2 & 0x40 and (b2 & 0x3F) == 1:   # flagpole: ball, pole, block at its foot
            put(c, 0, 0x24)
            for r in range(1, FLOOR_ROW):
                put(c, r, 0x25)
            put(c, FLOOR_ROW, SOLID_METATILES[kind_of_area])
        elif row == 0x0D and b2 & 0x40 and (b2 & 0x3F) == 0:   # intro pipe: the same, a short pipe above
            area.intro_pipe = sideways_pipe(c, 10, shaft_top=7)
            put(c + 2, 7, 0x10)
            put(c + 3, 7, 0x11)
        elif row in (0x0D, 0x0E):
            pass                                       # scroll locks and such; terrain changes (done above)
        elif strict:
            sys.exit("area %02X: object %02X %02X at column %d isn't handled yet" % (ptr, b1, b2, c))
    return area


def metatile_to_scenery(m):
    """SMB metatile number -> SCENERY_* number (SceneryTiles lists the groups in order)"""
    return sum(len(names) for names in METATILE_NAMES[:m >> 6]) + (m & 0x3F)


# ---- Music. SMB's music engine plays "headers": each points at data for its two
# squares, triangle and noise. Square 2 leads: [length byte (bit 7 set)] note,
# 0 ends the part. Square 1 and noise pack length and note in one byte, the
# triangle works like square 2. Notes index FreqRegLookupTbl; lengths index
# MusicLengthLookupTbl from the header's offset (+8 for the faster "hurry" tempo).
# The songs are simulated frame by frame and written out as per-channel
# (frames, note) lists for the Game Boy: SMB's squares -> pulse 1 and 2, triangle
# -> wave, noise -> noise.
SOUND_BANK = 4
MUSIC_HEADERS = 0xF90D       # MusicHeaderData (song offsets first, then headers)
FREQ_TABLE = 0xFF00          # FreqRegLookupTbl
LENGTH_TABLE = 0xFF66        # MusicLengthLookupTbl
NES_CPU_HZ = 1789773
HURRY_LENGTHS = 8
# Song numbers in MusicHeaderData's list
EVENT_DEATH, EVENT_GAME_OVER, EVENT_END_OF_LEVEL, EVENT_HURRY = 0, 1, 5, 6
AREA_UNDERGROUND, AREA_STAR, AREA_PIPE_INTRO = 10, 12, 13
GROUND_LAYOUT, GROUND_LAYOUT_END, GROUND_LOOP = 16, 49, 17   # the ground theme's parts, and where it loops back to
TRIANGLE_SHORT = 8           # frames a triangle note sounds for SMB's linear counter $1F
TRIANGLE_LONG_FROM = 0x12    # event music holds notes this long or longer ($FF)
# Game Boy pulse envelope per song (NRx2: start volume, fade speed): SMB's area
# music is plucky, its event music (fanfares) held
VOICE_AREA, VOICE_UNDERGROUND, VOICE_EVENT = 0xB2, 0xB1, 0xA5


def music_part(prg, offset, fast, event):
    """{channel: [(frames, note)]} for one part; note 0 is a rest (noise: drum kind 1-3)"""
    rd = lambda a: prg[a - 0x8000]
    h = [rd(MUSIC_HEADERS + offset + k) for k in range(6)]
    lenofs, data, tri, sq1, noise = h[0] + fast, h[1] | (h[2] << 8), h[3], h[4], h[5] if not event else 0
    length = lambda i: rd(LENGTH_TABLE + (i & 7) + lenofs)
    alt = lambda v: ((v & 1) << 2) | ((v >> 7) << 1) | ((v >> 6) & 1)
    note = lambda v: 0 if rd(FREQ_TABLE + v) == 0 and rd(FREQ_TABLE + v + 1) == 0 else v >> 1
    out = {}
    lead, i, n = [], 0, 0
    while rd(data + i):
        v = rd(data + i); i += 1
        if v & 0x80:
            n = length(v); v = rd(data + i); i += 1
        lead.append((n, note(v)))
    out['pulse2'] = lead
    total = sum(n for n, _ in lead)

    def fit(events):   # exactly `total` frames: cut the overhang, pad with a rest
        fitted, t = [], 0
        for n, v in events:
            n = min(n, total - t)
            if n > 0:
                fitted.append((n, v)); t += n
        if t < total:
            fitted.append((total - t, 0))
        return fitted

    if sq1:
        ev, i, t = [], sq1, 0
        while t < total:
            v = rd(data + i); i += 1
            if v == 0:
                continue          # death music's sweep switch
            n = length(alt(v)); ev.append((n, note(v & 0x3E))); t += n
        out['pulse1'] = fit(ev)
    if tri:
        ev, i, t, n = [], tri, 0, 0
        while t < total:
            v = rd(data + i); i += 1
            if v == 0:
                break             # silent for the rest of the part
            if v & 0x80:
                n = length(v); v = rd(data + i); i += 1
                if v == 0:
                    break
            sound = n if (event and n >= TRIANGLE_LONG_FROM) else min(n, TRIANGLE_SHORT)
            ev.append((sound, note(v)))
            if n > sound:
                ev.append((n - sound, 0))
            t += n
        out['wave'] = fit(ev)
    if noise:
        ev, i, t = [], noise, 0
        while t < total:
            v = rd(data + i); i += 1
            if v == 0:
                i = noise; continue   # the beat loops for as long as the part lasts
            k = v & 0x3E
            ev.append((length(alt(v)), 3 if k == 0x30 else 2 if k == 0x20 else 1 if k & 0x10 else 0))
            t += ev[-1][0]
        out['noise'] = fit(ev)
    return out


def write_music(prg):
    """Music (bank 4): SMB's songs for the Game Boy's sound channels"""
    rd = lambda a: prg[a - 0x8000]
    offsets = [rd(MUSIC_HEADERS + i) for i in range(GROUND_LAYOUT_END)]
    ground = list(range(GROUND_LAYOUT, GROUND_LAYOUT_END))
    songs = [  # name, song numbers of its parts, part it loops back to (None: plays once), event music, voice
        ("GROUND", ground, GROUND_LOOP - GROUND_LAYOUT, 0, False, VOICE_AREA),
        ("GROUND_FAST", ground, GROUND_LOOP - GROUND_LAYOUT, HURRY_LENGTHS, False, VOICE_AREA),
        ("UNDERGROUND", [AREA_UNDERGROUND], 0, 0, False, VOICE_UNDERGROUND),
        ("UNDERGROUND_FAST", [AREA_UNDERGROUND], 0, HURRY_LENGTHS, False, VOICE_UNDERGROUND),
        ("STAR", [AREA_STAR], 0, 0, False, VOICE_AREA),
        ("STAR_FAST", [AREA_STAR], 0, HURRY_LENGTHS, False, VOICE_AREA),
        ("HURRY", [EVENT_HURRY], None, 0, True, VOICE_EVENT),
        ("DEATH", [EVENT_DEATH], None, 0, True, VOICE_EVENT),
        ("GAME_OVER", [EVENT_GAME_OVER], None, 0, True, VOICE_EVENT),
        ("LEVEL_CLEAR", [EVENT_END_OF_LEVEL], None, 0, True, VOICE_EVENT),
        ("PIPE_INTRO", [AREA_PIPE_INTRO], None, 0, False, VOICE_AREA),
    ]
    channels = ['pulse1', 'pulse2', 'wave', 'noise']
    parts, part_index, streams = [], {}, {}

    def stream(events):
        data = []
        for n, v in events:
            while n > 255:
                data += [255, v]; n -= 255
            data += [n, v]
        key = tuple(data + [0])
        if key not in streams:
            streams[key] = "musicStream%d" % len(streams)
        return streams[key]

    song_parts = []
    for name, numbers, loop, fast, event, voice in songs:
        idx = []
        for number in numbers:
            key = (offsets[number], fast, event)
            if key not in part_index:
                decoded = music_part(prg, offsets[number], fast, event)
                part_index[key] = len(parts)
                parts.append([stream(decoded[c]) if c in decoded else None for c in channels])
            idx.append(part_index[key])
        song_parts.append(idx)

    # Game Boy frequencies (pulse, and wave with a 32-step wave: the same register
    # value for the same NES timer, as the triangle is also an octave lower)
    freqs = []
    for v in range(0, 0x80, 2):
        hi, lo = rd(FREQ_TABLE + v), rd(FREQ_TABLE + v + 1)
        t = (hi << 8) | lo
        freqs.append(0 if t == 0 else max(0, round(2048 - 131072 * 16 * (t + 1) / NES_CPU_HZ)))

    h = ["/*", " MUSIC.H", "",
         " Super Mario Bros.' music for the Game Boy, read from its own music data. A song",
         " is a list of parts; a part has a stream per channel (pulse 1, pulse 2, wave,",
         " noise; NULL = unused) of (frames, note) byte pairs ending with 0. Notes index",
         " MusicFreqs (0 = rest); the noise channel's are drum kinds 1-3.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/",
         "#ifndef __Music_h_INCLUDE", "#define __Music_h_INCLUDE", "",
         "#include <gbdk/platform.h>", "#include <stdint.h>", ""]
    for n, song in enumerate(songs):
        h.append("#define MUSIC_%-18s %d" % (song[0], n))
    h += ["#define MusicSongCount %d" % len(songs), "",
          "#define MUSIC_CHANNELS 4",
          "typedef struct { const uint8_t *channel[MUSIC_CHANNELS]; } MusicPart;",
          "// loop: index of the part it loops back to, MUSIC_NO_LOOP if it plays once",
          "#define MUSIC_NO_LOOP 0xFF",
          "typedef struct { const uint8_t *parts; uint8_t count, loop, voice; } MusicSong;", "",
          "// In ROM bank %d (sound): switch to BANK(Music) before reading them" % SOUND_BANK,
          "BANKREF_EXTERN(Music)",
          "extern const MusicSong MusicSongs[];", "extern const MusicPart MusicParts[];",
          "extern const uint16_t MusicFreqs[];", "", "#endif", ""]
    c = ["/*", " MUSIC.C", "", " See Music.h.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/", "",
         "#pragma bank %d" % SOUND_BANK, "", "#include <gbdk/platform.h>", "#include \"Music.h\"", "",
         "BANKREF(Music)", ""]
    for key, name in streams.items():
        c.append("static const uint8_t %s[] = {%s};" % (name, ",".join(str(v) for v in key)))
    c += ["", "const MusicPart MusicParts[] = {"]
    for p in parts:
        c.append("  {{%s}}," % ", ".join(s if s else "NULL" for s in p))
    c += ["};", ""]
    for n, idx in enumerate(song_parts):
        c.append("static const uint8_t songParts%d[] = {%s};" % (n, ",".join(str(i) for i in idx)))
    c += ["", "const MusicSong MusicSongs[] = {"]
    for n, (name, numbers, loop, fast, event, voice) in enumerate(songs):
        c.append("  {songParts%d, %d, %s, 0x%02X}, // %s" % (n, len(song_parts[n]),
                 "MUSIC_NO_LOOP" if loop is None else loop, voice, name))
    c += ["};", "", "const uint16_t MusicFreqs[] = {"]
    c.append("  " + ",".join(str(f) for f in freqs))
    c += ["};", ""]
    folder = os.path.join(ROOT, "assets", "sound")
    os.makedirs(folder, exist_ok=True)
    open(os.path.join(folder, "Music.h"), "w", newline="\n").write("\n".join(h))
    open(os.path.join(folder, "Music.c"), "w", newline="\n").write("\n".join(c))
    size = sum(len(k) for k in streams) + len(parts) * 8 + sum(len(i) for i in song_parts) + len(songs) * 5 + len(freqs) * 2
    print("wrote assets/sound/Music.c/.h (%d songs, %d parts, about %d bytes)" % (len(songs), len(parts), size))

# ---- Levels: maps (bank 1), where their pipes go, and where their enemies start
AREA_1_2_INTRO, AREA_1_2 = 0x29, 0xC0
PIPE_INTRO_WIDTH = 20            # the 1-2 intro's screen, up to its scroll lock
SCROLL_LOCKS = (5, 6, 7)         # row 13 objects that stop the screen scrolling
# SMB keeps Mario's y as the top of a 32-pixel box: his feet are 32 below it
SMB_FEET = 32


def area_width(prg, ptr, first_page=0, to_scroll_lock=True):
    """columns from first_page up to the next scroll lock (or the end of the area)"""
    i = area_address(prg, ptr, AREA_DATA_H_OFFSETS, AREA_DATA_LOW, AREA_DATA_HIGH) - 0x8000 + 2
    page, last = 0, 0
    while prg[i] != 0xFD:
        b1, b2 = prg[i], prg[i + 1]
        if b2 & 0x80:
            page += 1
        if b1 & 0x0F == 0x0D and not (b2 & 0x40):
            page = b2 & 0x1F
        column = page * 16 + (b1 >> 4)
        if column >= first_page * 16 + 1:
            if to_scroll_lock and b1 & 0x0F == 0x0D and b2 & 0x40 and (b2 & 0x3F) in SCROLL_LOCKS:
                return column - first_page * 16
            last = max(last, column)
        i += 2
    return last + 1 - first_page * 16


def warp_for(prg, ptr, world, first_page, pages=16):
    """the area's warp for `world` on its pages first_page.. (destination area, page there)"""
    for page, dest, w, dest_page in read_warps(prg, ptr):
        if w == world and first_page <= page < first_page + pages:
            return dest, dest_page
    return None


def pipe_on_page(area, page):
    return [p for p in area.pipes if page * 16 <= p[0] < page * 16 + 16][0]


def start_feet(header):
    """where SMB drops Mario in (x, y of his feet), from the area header's start position"""
    return PLAYER_START_X & ~15, PLAYER_START_Y[(header[0] >> 3) & 7] + SMB_FEET


def write_map(name, grid, first, width, comment, defines):
    """assets/maps/<name>.c/.h: a grid of SCENERY_* blocks, width by 15, row by row"""
    rows = [[0] * width for _ in range(AREA_ROWS + MAP_ROW_OFFSET)]
    for c in range(width):
        for r in range(AREA_ROWS):
            m = grid[first + c][r]
            rows[r + MAP_ROW_OFFSET][c] = metatile_to_scenery(m) if m else 0
    guard = "__%s_h_INCLUDE" % name
    h = ["/*", " %s.H" % name.upper(), ""] + [" " + l for l in comment] + [
         "", " A grid of 16x16 blocks (SCENERY_* numbers), %d wide by %d tall, row by row." % (width, len(rows)),
         " Block rows are the map's (SMB's rows 0-12 are its rows 2-14).", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/",
         "#ifndef %s" % guard, "#define %s" % guard, "", "#include <gbdk/platform.h>", "",
         "#define %sWidth %d" % (name, width), "#define %sHeight %d" % (name, len(rows)), ""]
    for comment_line, macro, value in defines:
        if comment_line:
            h.append("// " + comment_line)
        h.append("#define %s %d" % (macro, value))
    h += ["", "// In switchable ROM bank 1 (maps): switch to BANK(%s) before reading it" % name,
          "BANKREF_EXTERN(%s)" % name, "extern const unsigned char %s[];" % name, "", "#endif", ""]
    c = ["/*", " %s.C" % name.upper(), "", " See %s.h." % name, "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/", "",
         "#pragma bank 1", "", "#include <gbdk/platform.h>", "", "BANKREF(%s)" % name, "",
         "const unsigned char %s[] =" % name, "{"]
    for row in rows:
        c.append("  " + ",".join("%3d" % v for v in row) + ",")
    c += ["};", ""]
    out = os.path.join(ROOT, "assets", "maps", name)
    open(out + ".h", "w", newline="\n").write("\n".join(h))
    open(out + ".c", "w", newline="\n").write("\n".join(c))
    print("wrote assets/maps/%s.c/.h (%dx%d)" % (name, width, len(rows)))


COIN_ROOMS = 0x42                # the underground area holding the coin rooms, page by page


def write_coin_room(prg, name, level, from_ptr, areas):
    """a coin room that the level area `from_ptr`'s pipe leads to, and where its pipes are;
    `areas` has the decoded level areas by pointer (SMB's pointers can differ in bit 7)"""
    level_prefix = "LEVEL" + level.replace("-", "_")
    room_prefix = level_prefix + "_BONUS"
    page, _, _, room_page = [w for w in read_warps(prg, from_ptr) if w[2] == 0 and w[1] == COIN_ROOMS][0]
    entry = [p for p in areas[from_ptr & 0x7F].pipes if p[2] and p[0] >= page * 16][0]
    width = area_width(prg, COIN_ROOMS, room_page)
    room = decode_area(prg, COIN_ROOMS, room_page * 16 + width)
    back_ptr, back_page = warp_for(prg, COIN_ROOMS, 0, room_page, 2)
    back = pipe_on_page(areas[back_ptr & 0x7F], back_page)
    x, feet = start_feet(room.header)
    write_map(name, room.grid, room_page * 16, width,
              ["World %s's underground coin room, read from Super Mario Bros.' own level data," % level,
               "and where the pipes in and out of it are."],
              [("%s's pipe that leads here: its left block column, and the block row of its top" % level,
                level_prefix + "_PIPE_COLUMN", entry[0]),
               (None, level_prefix + "_PIPE_ROW", entry[1] + MAP_ROW_OFFSET),
               ("Where Mario drops into the room (level pixels: his left, and his feet)", room_prefix + "_START_X", x),
               (None, room_prefix + "_START_FEET", feet),
               ("The way out: the sideways pipe's mouth (block column, block row of its top half)",
                room_prefix + "_EXIT_COLUMN", room.exit_pipe[0] - room_page * 16),
               (None, room_prefix + "_EXIT_ROW", room.exit_pipe[1] + MAP_ROW_OFFSET),
               ("...which leads back to %s's pipe here (left block column, block row of its top)" % level,
                level_prefix + "_RETURN_PIPE_COLUMN", back[0]),
               (None, level_prefix + "_RETURN_PIPE_ROW", back[1] + MAP_ROW_OFFSET)])


def write_levels(prg):
    """World 1-1's coin room; World 1-2 (its intro, the level, its coin room); every level's enemies"""
    # 1-1's map is hand-made (assets/maps/Level1_1.c); SMB's data says where its pipes go
    area_1_1 = decode_area(prg, AREA_1_1, 16 * 14, strict=False)
    areas = {AREA_1_1 & 0x7F: area_1_1}
    write_coin_room(prg, "Level1_1Bonus", "1-1", AREA_1_1, areas)

    # 1-2: the intro (Mario walks from the castle into a pipe), then the level underground
    intro = decode_area(prg, AREA_1_2_INTRO, PIPE_INTRO_WIDTH)
    x, feet = start_feet(intro.header)
    write_map("Level1_2Intro", intro.grid, 0, PIPE_INTRO_WIDTH,
              ["World 1-2's intro, read from Super Mario Bros.' own level data: Mario walks",
               "from the castle into the pipe (the level itself is underground, Level1_2)."],
              [("Where Mario starts (level pixels: his left, and his feet)", "LEVEL1_2_INTRO_START_X", x),
               (None, "LEVEL1_2_INTRO_START_FEET", feet),
               ("The pipe he walks into: its mouth (block column, block row of its top half)",
                "LEVEL1_2_INTRO_PIPE_COLUMN", intro.intro_pipe[0]),
               (None, "LEVEL1_2_INTRO_PIPE_ROW", intro.intro_pipe[1] + MAP_ROW_OFFSET)])
    width = area_width(prg, AREA_1_2, to_scroll_lock=False)   # (the warp zone is past one)
    level = decode_area(prg, AREA_1_2, width)
    areas[AREA_1_2 & 0x7F] = level
    enemies_1_2 = read_enemy_list(prg, area_address(prg, AREA_1_2, ENEMY_ADDR_H_OFFSETS, ENEMY_DATA_LOW, ENEMY_DATA_HIGH))
    warp_zone = [x for x, y, kind in enemies_1_2 if kind == "WARP_ZONE"][0] // 16
    warp_pipes = [p for p in level.pipes if p[2] and p[0] >= warp_zone]
    exit_area, exit_page = warp_for(prg, AREA_1_2, 0, 10)
    exit_to = pipe_on_page(area_1_1, exit_page)
    x, feet = start_feet(level.header)
    write_map("Level1_2", level.grid, 0, width,
              ["World 1-2, read from Super Mario Bros.' own level data."],
              [("Where Mario drops in (level pixels: his left, and his feet)", "LEVEL1_2_START_X", x),
               (None, "LEVEL1_2_START_FEET", feet),
               ("The way out: the sideways pipe's mouth (block column, block row of its top half),",
                "LEVEL1_2_EXIT_COLUMN", level.exit_pipe[0]),
               (None, "LEVEL1_2_EXIT_ROW", level.exit_pipe[1] + MAP_ROW_OFFSET),
               ("which comes out of 1-1's pipe here (SMB reuses 1-1's end for 1-2's)",
                "LEVEL1_2_EXIT_PIPE_COLUMN", exit_to[0]),
               (None, "LEVEL1_2_EXIT_PIPE_ROW", exit_to[1] + MAP_ROW_OFFSET),
               ("The warp zone: its text starts at this block column, and its pipes (to worlds 4, 3, 2)",
                "LEVEL1_2_WARP_ZONE_COLUMN", warp_zone)] +
              [(None, "LEVEL1_2_WARP_PIPE%d_COLUMN" % (n + 1), p[0]) for n, p in enumerate(warp_pipes)] +
              [(None, "LEVEL1_2_WARP_PIPE_ROW", warp_pipes[0][1] + MAP_ROW_OFFSET)])
    write_coin_room(prg, "Level1_2Bonus", "1-2", AREA_1_2, areas)

    # Every pipe outside 1-1 has a Piranha Plant (SMB adds one to each pipe it draws),
    # except the warp zone's
    for column, top, _ in level.pipes:
        if column < warp_zone:
            enemies_1_2.append((column * 16 + 8, (top + MAP_ROW_OFFSET) * 16, "PIRANHA"))
    write_level_info(prg, [(1, 1), (1, 2)])
    write_enemy_lists([
        ("Level1_1Enemies", "World 1-1", read_enemy_list(prg, ENEMY_LIST_1_1)),
        ("Level1_2Enemies", "World 1-2", [e for e in enemies_1_2 if e[2] != "WARP_ZONE"]),
    ])


HALFWAY_PAGES = 0x91BD   # HalfwayPageNybbles: per world 2 bytes, a nybble per level (1-1's first, high)


def write_level_info(prg, levels):
    """LevelInfo.h: each level's halfway point (the page a restart after dying
    starts from, once Mario's got that far)"""
    h = ["/*", " LEVELINFO.H", "",
         " Things about each level from Super Mario Bros.' own tables. The halfway point",
         " (HalfwayPageNybbles) is a page (16 blocks): once the screen has scrolled that",
         " far, dying restarts the level from there instead of the beginning.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/",
         "#ifndef __LevelInfo_h_INCLUDE", "#define __LevelInfo_h_INCLUDE", ""]
    for world, level in levels:
        byte = prg[HALFWAY_PAGES - 0x8000 + (world - 1) * 2 + (level - 1) // 2]
        page = byte >> 4 if level % 2 else byte & 0x0F
        h.append("#define LEVEL%d_%d_HALFWAY_PAGE %d" % (world, level, page))
    h += ["", "#endif", ""]
    open(os.path.join(ROOT, "assets", "maps", "LevelInfo.h"), "w", newline="\n").write("\n".join(h))
    print("wrote assets/maps/LevelInfo.h")


def write_enemy_lists(lists):
    """LevelEnemies (bank 1, with the maps): where each level's enemies start"""
    h = ["/*", " LEVELENEMIES.H", "",
         " Where each level's enemies start, read from Super Mario Bros.' own enemy lists.",
         " 4 bytes each, sorted by x: x (low, high) and y in level pixels (the top-left of",
         " the body, standing on the ground or a platform; a Piranha Plant's is inside its",
         " pipe, a lift's its top), then the ENEMY_* type.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/",
         "#ifndef __LevelEnemies_h_INCLUDE", "#define __LevelEnemies_h_INCLUDE", "",
         "#include <gbdk/platform.h>", ""]
    for n, kind in enumerate(ENEMY_TYPES):
        h.append("#define ENEMY_%-10s %d" % (kind, n))
    h.append("")
    c = ["/*", " LEVELENEMIES.C", "", " See LevelEnemies.h.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/", "",
         "#pragma bank 1", "", "#include <gbdk/platform.h>", "", "BANKREF(LevelEnemies)", ""]
    for name, level, enemies in lists:
        enemies = sorted(enemies)   # by x: the game's spawn window relies on it
        h += ["#define %sCount %d" % (name, len(enemies)), "extern const unsigned char %s[];" % name]
        c += ["// %s" % level, "const unsigned char %s[] =" % name, "{"]
        for x, y, kind in enemies:
            c.append("  0x%02X,0x%02X, %3d, %d, // %s at block %g" % (x & 255, x >> 8, y, ENEMY_TYPES.index(kind),
                                                                   kind.lower(), x / 16))
        c += ["};", ""]
    h += ["", "// In switchable ROM bank 1 (maps): switch to BANK(LevelEnemies) before reading them",
          "BANKREF_EXTERN(LevelEnemies)", "", "#endif", ""]
    out = os.path.join(ROOT, "assets", "maps", "LevelEnemies")
    open(out + ".h", "w", newline="\n").write("\n".join(h))
    open(out + ".c", "w", newline="\n").write("\n".join(c))
    for old in ("Level1_1Enemies.c", "Level1_1Enemies.h"):   # (now part of LevelEnemies)
        if os.path.exists(os.path.join(ROOT, "assets", "maps", old)):
            os.remove(os.path.join(ROOT, "assets", "maps", old))
    print("wrote assets/maps/LevelEnemies.c/.h (%s)" % ", ".join("%s: %d" % (n, len(e)) for n, _, e in lists))

# SMB's metatile tables (MetatileGraphics_Low/High) in PRG: 4 palette groups,
# 4 tile numbers per metatile in TL, BL, TR, BR order. Names follow the disassembly.
METATILE_TABLE = 0x8B08
METATILE_NAMES = [
    ["BLANK", "BLACK", "BUSH_LEFT", "BUSH_MIDDLE", "BUSH_RIGHT", "HILL_LEFT", "HILL_LEFT_BOTTOM",
     "HILL_TOP", "HILL_RIGHT", "HILL_RIGHT_BOTTOM", "HILL_BOTTOM", "BRIDGE_RAIL", "CHAIN",
     "TALL_TREE_TOP", "SHORT_TREE", "TALL_TREE_BOTTOM", "PIPE_TOP_LEFT", "PIPE_TOP_RIGHT",
     "DECOR_PIPE_TOP_LEFT", "DECOR_PIPE_TOP_RIGHT", "PIPE_LEFT", "PIPE_RIGHT", "TREE_LEDGE_LEFT",
     "TREE_LEDGE_MIDDLE", "TREE_LEDGE_RIGHT", "MUSHROOM_LEFT", "MUSHROOM_MIDDLE", "MUSHROOM_RIGHT",
     "SIDE_PIPE_END_TOP", "SIDE_PIPE_TOP", "SIDE_PIPE_JOINT_TOP", "SIDE_PIPE_END_BOTTOM",
     "SIDE_PIPE_BOTTOM", "SIDE_PIPE_JOINT_BOTTOM", "SEAPLANT", "BLANK_HIT", "FLAGPOLE_BALL",
     "FLAGPOLE", "BLANK_VINE"],
    ["ROPE_VERTICAL", "ROPE_HORIZONTAL", "PULLEY_LEFT", "PULLEY_RIGHT", "BLANK_ROPE", "CASTLE_TOP",
     "CASTLE_WINDOW_LEFT", "CASTLE_WALL", "CASTLE_WINDOW_RIGHT", "CASTLE_TOP_BRICK", "CASTLE_DOOR_TOP",
     "CASTLE_DOOR", "LEDGE_STUMP", "FENCE", "TREE_TRUNK", "MUSHROOM_STUMP_TOP", "MUSHROOM_STUMP",
     "BRICK_LINE", "BRICK", "BRICK_UNUSED", "ROCK", "BRICK_LINE_POWERUP", "BRICK_LINE_VINE",
     "BRICK_LINE_STAR", "BRICK_LINE_COINS", "BRICK_LINE_1UP", "BRICK_POWERUP", "BRICK_VINE",
     "BRICK_STAR", "BRICK_COINS", "BRICK_1UP", "HIDDEN_COIN", "HIDDEN_1UP", "STAIR_BLOCK",
     "WHITE_WALL", "BRIDGE", "CANNON_BARREL", "CANNON_TOP", "CANNON_BOTTOM", "BLANK_SPRING",
     "HALF_BRICK_SPRING", "WATER_ROCK", "HALF_BRICK", "WATER_PIPE_TOP", "WATER_PIPE_BOTTOM",
     "FLAG_BALL"],
    ["CLOUD_LEFT", "CLOUD_MIDDLE", "CLOUD_RIGHT", "CLOUD_BOTTOM_LEFT", "CLOUD_BOTTOM_MIDDLE",
     "CLOUD_BOTTOM_RIGHT", "WATER_TOP", "WATER", "CLOUD_GROUND", "BOWSER_BRIDGE"],
    ["QUESTION_COIN", "QUESTION_POWERUP", "COIN", "WATER_COIN", "USED_BLOCK", "AXE"],
]


def write_scenery(chr_, grays):
    """SceneryTiles: unique tiles plus a table of 4 tile indexes per metatile"""
    prg = chr_.prg
    base = METATILE_TABLE - 0x8000
    pointers = [prg[base + k] | (prg[base + 4 + k] << 8) for k in range(4)]
    unique = {}      # gb bytes -> index
    tiles = []       # (bytes, comment)
    table = []       # (name, [TL, TR, BL, BR] tile indexes)
    for group, names in enumerate(METATILE_NAMES):
        for m, name in enumerate(names):
            o = pointers[group] - 0x8000 + m * 4
            tl, bl, tr, br = prg[o:o + 4]
            idx = []
            for nes in (tl, tr, bl, br):
                data = tuple(to_gb(chr_.tile(BG + nes), grays[group]))
                if data not in unique:
                    unique[data] = len(tiles)
                    tiles.append((list(data), "nes bg %02X (palette %d)" % (nes, group)))
                idx.append(unique[data])
            table.append((name, idx))

    h = ["/*", " SCENERYTILES.H", "",
         " Every 16x16 background block (metatile) Super Mario Bros. can draw: overworld,",
         " underground, castle, water and sky scenery, blocks, pipes, bridges, the axe...",
         " SceneryTiles holds the unique 8x8 tiles; SceneryMetatiles holds 4 tile indexes",
         " per block (TL, TR, BL, BR) and SCENERY_<NAME> is a block's number in it.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/",
         "#ifndef __SceneryTiles_h_INCLUDE", "#define __SceneryTiles_h_INCLUDE", "",
         "#include <gbdk/platform.h>", "",
         "#define SceneryTilesCount %d" % len(tiles),
         "#define SceneryMetatileCount %d" % len(table), ""]
    for n, (name, idx) in enumerate(table):
        h.append("#define SCENERY_%-26s %3d" % (name, n))
    h += ["", "// In a switchable ROM bank: switch to BANK(SceneryTiles) before reading either array",
          "BANKREF_EXTERN(SceneryTiles)", "extern const unsigned char SceneryTiles[];",
          "extern const unsigned char SceneryMetatiles[];", "", "#endif", ""]
    c = ["/*", " SCENERYTILES.C", "", " See SceneryTiles.h.", "",
         " Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.",
         " Do not edit; change the script and rerun it.", "*/", "",
         "#pragma bank %d" % GRAPHICS_BANK, "", "#include <gbdk/platform.h>", "", "BANKREF(SceneryTiles)", "",
         "const unsigned char SceneryTiles[] =", "{"]
    for data, comment in tiles:
        c.append("  " + ",".join("0x%02X" % v for v in data) + ", // " + comment)
    c += ["};", "", "// 4 SceneryTiles indexes per block: TL, TR, BL, BR",
          "const unsigned char SceneryMetatiles[] =", "{"]
    for name, idx in table:
        c.append("  " + ",".join("%3d" % v for v in idx) + ", // " + name)
    c += ["};", ""]
    out = os.path.join(ROOT, "assets", "tiles", "SceneryTiles")
    open(out + ".h", "w", newline="\n").write("\n".join(h))
    open(out + ".c", "w", newline="\n").write("\n".join(c))
    print("wrote assets/tiles/SceneryTiles.c/.h (%d tiles, %d blocks)" % (len(tiles), len(table)))


if __name__ == "__main__":
    main()
