/*
 MUSIC.H

 Super Mario Bros.' music for the Game Boy, read from its own music data. A song
 is a list of parts; a part has a stream per channel (pulse 1, pulse 2, wave,
 noise; NULL = unused) of (frames, note) byte pairs ending with 0. Notes index
 MusicFreqs (0 = rest); the noise channel's are drum kinds 1-3.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __Music_h_INCLUDE
#define __Music_h_INCLUDE

#include <gbdk/platform.h>
#include <stdint.h>

#define MUSIC_GROUND             0
#define MUSIC_GROUND_FAST        1
#define MUSIC_UNDERGROUND        2
#define MUSIC_UNDERGROUND_FAST   3
#define MUSIC_STAR               4
#define MUSIC_STAR_FAST          5
#define MUSIC_HURRY              6
#define MUSIC_DEATH              7
#define MUSIC_GAME_OVER          8
#define MUSIC_LEVEL_CLEAR        9
#define MusicSongCount 10

#define MUSIC_CHANNELS 4
typedef struct { const uint8_t *channel[MUSIC_CHANNELS]; } MusicPart;
// loop: index of the part it loops back to, MUSIC_NO_LOOP if it plays once
#define MUSIC_NO_LOOP 0xFF
typedef struct { const uint8_t *parts; uint8_t count, loop, voice; } MusicSong;

// In ROM bank 4 (sound): switch to BANK(Music) before reading them
BANKREF_EXTERN(Music)
extern const MusicSong MusicSongs[];
extern const MusicPart MusicParts[];
extern const uint16_t MusicFreqs[];

#endif
