/*
 MUSIC.C

 See Music.h.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/

#pragma bank 4

#include <gbdk/platform.h>
#include "Music.h"

BANKREF(Music)

static const uint8_t musicStream0[] = {9,16,18,16,18,16,9,16,18,16,18,21,18,0,36,17,0};
static const uint8_t musicStream1[] = {9,26,18,26,18,26,9,22,18,26,36,29,36,0,0};
static const uint8_t musicStream2[] = {8,12,1,0,8,12,10,0,8,12,10,0,8,12,1,0,8,12,1,0,8,0,1,0,8,29,28,0,8,17,28,0,0};
static const uint8_t musicStream3[] = {18,3,9,1,18,3,9,1,18,3,27,3,18,3,9,1,9,1,9,1,0};
static const uint8_t musicStream4[] = {27,14,27,10,27,6,18,10,18,12,9,11,18,10,12,10,12,17,12,21,18,22,9,19,18,21,18,19,9,14,9,15,27,12,0};
static const uint8_t musicStream5[] = {27,22,27,17,27,14,18,19,18,21,9,20,9,19,9,0,12,17,12,26,12,29,9,32,9,0,9,27,18,29,18,26,9,22,9,24,27,21,0};
static const uint8_t musicStream6[] = {8,17,19,0,8,14,19,0,8,10,19,0,8,15,10,0,8,17,10,0,8,16,1,0,8,15,1,0,8,0,1,0,8,14,4,0,8,22,4,0,8,26,4,0,8,27,1,0,8,0,1,0,8,24,1,0,8,26,1,0,8,0,1,0,8,22,1,0,8,0,1,0,8,19,1,0,8,21,1,0,8,17,19,0,0};
static const uint8_t musicStream7[] = {18,2,6,1,6,0,6,1,18,3,6,1,6,0,6,1,18,2,6,1,6,0,6,1,18,3,6,1,6,0,6,1,18,2,6,1,6,0,6,1,18,3,6,1,6,0,6,1,18,2,6,1,6,0,6,1,18,3,6,1,6,0,6,1,0};
static const uint8_t musicStream8[] = {18,0,9,26,9,25,9,24,18,21,9,22,9,0,9,14,9,15,9,17,9,0,9,10,9,14,9,15,0};
static const uint8_t musicStream9[] = {18,0,9,29,9,28,9,27,9,25,9,0,9,26,9,0,9,18,9,19,9,22,9,0,9,19,9,22,9,24,0};
static const uint8_t musicStream10[] = {8,10,19,0,8,17,19,0,8,22,10,0,8,15,19,0,8,22,1,0,8,22,10,0,8,15,10,0,0};
static const uint8_t musicStream11[] = {18,2,6,1,6,0,6,1,18,3,6,1,6,0,6,1,18,2,6,1,6,0,6,1,18,3,6,1,6,0,6,1,0};
static const uint8_t musicStream12[] = {18,0,9,26,9,25,9,24,18,21,9,22,9,0,18,27,9,27,9,27,27,0,0};
static const uint8_t musicStream13[] = {18,0,9,29,9,28,9,27,9,25,9,0,9,26,9,0,9,50,9,0,9,50,36,50,0};
static const uint8_t musicStream14[] = {8,10,19,0,8,14,19,0,8,17,1,0,8,22,10,0,8,39,10,0,8,39,1,0,8,39,10,0,8,17,10,0,0};
static const uint8_t musicStream15[] = {18,0,9,18,18,0,9,15,18,0,36,14,36,0,0};
static const uint8_t musicStream16[] = {18,0,27,25,27,24,36,22,36,0,0};
static const uint8_t musicStream17[] = {8,10,10,0,8,18,19,0,8,20,19,0,8,22,19,0,8,17,1,0,8,17,10,0,8,10,10,0,0};
static const uint8_t musicStream18[] = {9,18,18,18,18,18,9,18,18,20,9,17,18,14,9,14,36,10,0};
static const uint8_t musicStream19[] = {9,22,18,22,18,22,9,22,9,24,9,0,9,26,9,22,9,0,9,19,36,17,0};
static const uint8_t musicStream20[] = {8,7,19,0,8,13,19,0,8,18,10,0,8,17,19,0,8,10,19,0,8,6,10,0,0};
static const uint8_t musicStream21[] = {9,18,18,18,18,18,9,18,9,20,27,17,54,0,0};
static const uint8_t musicStream22[] = {9,22,9,22,9,0,9,22,9,0,9,22,9,24,27,26,27,0,27,0,0};
static const uint8_t musicStream23[] = {9,22,18,19,27,14,18,14,9,15,18,22,9,22,36,15,0};
static const uint8_t musicStream24[] = {9,26,18,22,27,17,18,18,9,19,9,27,9,0,9,27,36,19,0};
static const uint8_t musicStream25[] = {8,10,19,0,8,16,1,0,8,17,10,0,8,22,10,0,8,15,10,0,8,15,10,0,8,22,1,0,8,22,1,0,8,15,1,0,8,0,1,0,0};
static const uint8_t musicStream26[] = {27,1,9,1,18,3,18,1,27,1,9,1,18,3,18,1,0};
static const uint8_t musicStream27[] = {12,17,12,27,12,27,12,27,12,26,12,24,9,22,18,19,9,15,36,14,0};
static const uint8_t musicStream28[] = {12,21,12,32,12,32,12,32,12,29,12,27,9,26,9,22,9,0,9,19,36,17,0};
static const uint8_t musicStream29[] = {8,12,19,0,8,15,1,0,8,17,10,0,8,21,10,0,8,17,10,0,8,17,10,0,8,22,1,0,8,22,1,0,8,17,1,0,8,0,1,0,0};
static const uint8_t musicStream30[] = {9,17,18,24,9,24,12,24,12,22,12,21,9,17,18,14,9,14,36,10,0};
static const uint8_t musicStream31[] = {9,21,9,27,9,0,9,27,12,27,12,26,12,24,36,22,36,0,0};
static const uint8_t musicStream32[] = {8,17,19,0,8,17,1,0,8,17,4,0,8,19,4,0,8,21,4,0,8,22,10,0,8,17,10,0,8,10,28,0,0};
static const uint8_t musicStream33[] = {6,16,12,16,12,16,6,16,12,16,12,21,12,0,24,17,0};
static const uint8_t musicStream34[] = {6,26,12,26,12,26,6,22,12,26,24,29,24,0,0};
static const uint8_t musicStream35[] = {6,12,8,12,4,0,8,12,4,0,6,12,6,12,6,0,8,29,16,0,8,17,16,0,0};
static const uint8_t musicStream36[] = {12,3,6,1,12,3,6,1,12,3,18,3,12,3,6,1,6,1,6,1,0};
static const uint8_t musicStream37[] = {18,14,18,10,18,6,12,10,12,12,6,11,12,10,8,10,8,17,8,21,12,22,6,19,12,21,12,19,6,14,6,15,18,12,0};
static const uint8_t musicStream38[] = {18,22,18,17,18,14,12,19,12,21,6,20,6,19,6,0,8,17,8,26,8,29,6,32,6,0,6,27,12,29,12,26,6,22,6,24,18,21,0};
static const uint8_t musicStream39[] = {8,17,10,0,8,14,10,0,8,10,10,0,8,15,4,0,8,17,4,0,6,16,6,15,6,0,8,14,8,22,8,26,6,27,6,0,6,24,6,26,6,0,6,22,6,0,6,19,6,21,8,17,10,0,0};
static const uint8_t musicStream40[] = {12,2,4,1,4,0,4,1,12,3,4,1,4,0,4,1,12,2,4,1,4,0,4,1,12,3,4,1,4,0,4,1,12,2,4,1,4,0,4,1,12,3,4,1,4,0,4,1,12,2,4,1,4,0,4,1,12,3,4,1,4,0,4,1,0};
static const uint8_t musicStream41[] = {12,0,6,26,6,25,6,24,12,21,6,22,6,0,6,14,6,15,6,17,6,0,6,10,6,14,6,15,0};
static const uint8_t musicStream42[] = {12,0,6,29,6,28,6,27,6,25,6,0,6,26,6,0,6,18,6,19,6,22,6,0,6,19,6,22,6,24,0};
static const uint8_t musicStream43[] = {8,10,10,0,8,17,10,0,8,22,4,0,8,15,10,0,6,22,8,22,4,0,8,15,4,0,0};
static const uint8_t musicStream44[] = {12,2,4,1,4,0,4,1,12,3,4,1,4,0,4,1,12,2,4,1,4,0,4,1,12,3,4,1,4,0,4,1,0};
static const uint8_t musicStream45[] = {12,0,6,26,6,25,6,24,12,21,6,22,6,0,12,27,6,27,6,27,18,0,0};
static const uint8_t musicStream46[] = {12,0,6,29,6,28,6,27,6,25,6,0,6,26,6,0,6,50,6,0,6,50,24,50,0};
static const uint8_t musicStream47[] = {8,10,10,0,8,14,10,0,6,17,8,22,4,0,8,39,4,0,6,39,8,39,4,0,8,17,4,0,0};
static const uint8_t musicStream48[] = {12,0,6,18,12,0,6,15,12,0,24,14,24,0,0};
static const uint8_t musicStream49[] = {12,0,18,25,18,24,24,22,24,0,0};
static const uint8_t musicStream50[] = {8,10,4,0,8,18,10,0,8,20,10,0,8,22,10,0,6,17,8,17,4,0,8,10,4,0,0};
static const uint8_t musicStream51[] = {6,18,12,18,12,18,6,18,12,20,6,17,12,14,6,14,24,10,0};
static const uint8_t musicStream52[] = {6,22,12,22,12,22,6,22,6,24,6,0,6,26,6,22,6,0,6,19,24,17,0};
static const uint8_t musicStream53[] = {8,7,10,0,8,13,10,0,8,18,4,0,8,17,10,0,8,10,10,0,8,6,4,0,0};
static const uint8_t musicStream54[] = {6,18,12,18,12,18,6,18,6,20,18,17,36,0,0};
static const uint8_t musicStream55[] = {6,22,6,22,6,0,6,22,6,0,6,22,6,24,18,26,18,0,18,0,0};
static const uint8_t musicStream56[] = {6,22,12,19,18,14,12,14,6,15,12,22,6,22,24,15,0};
static const uint8_t musicStream57[] = {6,26,12,22,18,17,12,18,6,19,6,27,6,0,6,27,24,19,0};
static const uint8_t musicStream58[] = {8,10,10,0,6,16,8,17,4,0,8,22,4,0,8,15,4,0,8,15,4,0,6,22,6,22,6,15,6,0,0};
static const uint8_t musicStream59[] = {18,1,6,1,12,3,12,1,18,1,6,1,12,3,12,1,0};
static const uint8_t musicStream60[] = {8,17,8,27,8,27,8,27,8,26,8,24,6,22,12,19,6,15,24,14,0};
static const uint8_t musicStream61[] = {8,21,8,32,8,32,8,32,8,29,8,27,6,26,6,22,6,0,6,19,24,17,0};
static const uint8_t musicStream62[] = {8,12,10,0,6,15,8,17,4,0,8,21,4,0,8,17,4,0,8,17,4,0,6,22,6,22,6,17,6,0,0};
static const uint8_t musicStream63[] = {6,17,12,24,6,24,8,24,8,22,8,21,6,17,12,14,6,14,24,10,0};
static const uint8_t musicStream64[] = {6,21,6,27,6,0,6,27,8,27,8,26,8,24,24,22,24,0,0};
static const uint8_t musicStream65[] = {8,17,10,0,6,17,8,17,8,19,8,21,8,22,4,0,8,17,4,0,8,10,16,0,0};
static const uint8_t musicStream66[] = {9,10,9,22,9,49,9,19,9,8,9,20,54,0,9,10,9,22,9,49,9,19,9,8,9,20,54,0,9,4,9,15,9,47,9,12,9,48,9,13,54,0,9,4,9,15,9,47,9,12,9,48,9,13,36,0,6,13,6,12,6,11,18,10,18,13,18,12,18,7,18,6,18,11,6,10,6,16,6,15,6,14,6,20,6,19,12,18,12,13,12,9,12,8,12,49,12,7,54,0,54,0,0};
static const uint8_t musicStream67[] = {54,0,9,0,54,1,54,0,3,0,54,0,54,1,54,0,9,0,54,0,9,0,54,0,54,1,3,1,54,1,3,2,54,1,9,0,54,0,9,0,54,0,0};
static const uint8_t musicStream68[] = {6,10,6,22,6,49,6,19,6,8,6,20,36,0,6,10,6,22,6,49,6,19,6,8,6,20,36,0,6,4,6,15,6,47,6,12,6,48,6,13,36,0,6,4,6,15,6,47,6,12,6,48,6,13,24,0,4,13,4,12,4,11,12,10,12,13,12,12,12,7,12,6,12,11,4,10,4,16,4,15,4,14,4,20,4,19,8,18,8,13,8,9,8,8,8,49,8,7,36,0,36,0,0};
static const uint8_t musicStream69[] = {36,0,6,0,36,1,36,0,2,0,36,0,36,1,36,0,6,0,36,0,6,0,36,0,36,1,2,1,36,1,2,2,36,1,6,0,36,0,6,0,36,0,0};
static const uint8_t musicStream70[] = {12,15,12,15,12,15,6,12,12,15,12,15,6,12,6,15,6,12,12,15,12,14,12,14,12,14,6,10,12,14,12,14,6,10,6,14,6,10,12,14,0};
static const uint8_t musicStream71[] = {12,22,12,22,12,22,6,0,6,22,6,0,18,22,12,22,12,22,12,21,12,21,12,21,6,0,6,21,6,0,18,21,12,21,12,21,0};
static const uint8_t musicStream72[] = {8,12,16,0,8,19,10,0,8,24,10,0,8,0,4,0,8,19,4,0,8,24,4,0,8,10,16,0,8,17,10,0,8,22,10,0,8,0,4,0,8,17,4,0,8,22,4,0,0};
static const uint8_t musicStream73[] = {6,15,6,15,6,15,3,12,6,15,6,15,3,12,3,15,3,12,6,15,6,14,6,14,6,14,3,10,6,14,6,14,3,10,3,14,3,10,6,14,0};
static const uint8_t musicStream74[] = {6,22,6,22,6,22,3,0,3,22,3,0,9,22,6,22,6,22,6,21,6,21,6,21,3,0,3,21,3,0,9,21,6,21,6,21,0};
static const uint8_t musicStream75[] = {8,12,4,0,8,19,1,0,8,24,1,0,6,0,6,19,6,24,8,10,4,0,8,17,1,0,8,22,1,0,6,0,6,17,6,22,0};
static const uint8_t musicStream76[] = {6,2,2,1,2,0,2,1,6,3,2,1,2,0,2,1,6,2,2,1,2,0,2,1,6,3,2,1,2,0,2,1,6,2,2,1,2,0,2,1,6,3,2,1,2,0,2,1,6,2,2,1,2,0,2,1,6,3,2,1,2,0,2,1,0};
static const uint8_t musicStream77[] = {8,3,16,18,8,18,16,18,8,4,16,19,8,19,16,19,8,5,16,20,8,20,16,20,8,21,8,0,64,21,0};
static const uint8_t musicStream78[] = {8,14,8,24,8,0,8,24,8,24,8,0,8,15,8,25,8,0,8,25,8,25,8,0,8,16,8,26,8,0,8,26,8,26,8,0,8,27,8,0,64,27,0};
static const uint8_t musicStream79[] = {8,21,8,33,8,0,8,33,8,33,8,0,8,22,8,50,8,0,8,50,8,50,8,0,8,23,8,35,8,0,8,35,8,35,8,0,8,17,8,0,64,17,0};
static const uint8_t musicStream80[] = {3,20,3,21,3,22,27,0,9,17,18,24,9,24,12,24,12,22,12,21,9,17,18,14,9,14,36,10,0};
static const uint8_t musicStream81[] = {36,0,9,21,9,27,9,0,9,27,12,27,12,26,12,24,36,22,36,0,0};
static const uint8_t musicStream82[] = {36,0,27,17,8,17,1,0,8,17,4,0,8,19,4,0,8,21,4,0,18,22,18,17,36,10,0};
static const uint8_t musicStream83[] = {9,14,18,0,9,10,18,0,18,6,36,15,54,15,9,14,9,12,36,14,0};
static const uint8_t musicStream84[] = {9,22,9,0,9,0,9,17,9,0,9,0,18,14,12,19,12,21,12,19,18,18,18,20,18,18,54,17,0};
static const uint8_t musicStream85[] = {8,17,1,0,8,0,1,0,8,0,1,0,8,14,1,0,8,0,1,0,8,0,1,0,18,10,36,15,54,11,54,10,0};
static const uint8_t musicStream86[] = {8,6,8,10,8,14,8,17,8,22,8,26,24,29,24,26,8,7,8,10,8,13,8,18,8,22,8,25,24,30,24,25,8,8,8,12,8,15,8,20,8,24,8,27,24,31,8,31,8,31,8,31,36,26,0};
static const uint8_t musicStream87[] = {8,0,8,3,8,6,8,10,8,14,8,17,24,22,24,17,8,0,8,48,8,7,8,10,8,13,8,18,24,22,24,18,8,0,8,4,8,8,8,12,8,15,8,20,24,24,24,24,36,50,0};
static const uint8_t musicStream88[] = {24,0,8,10,8,14,8,17,24,26,8,22,4,0,8,0,4,0,8,0,4,0,8,0,4,0,8,10,8,13,8,18,24,25,8,22,4,0,8,0,4,0,24,0,8,12,8,15,8,20,24,27,8,24,8,24,8,24,36,22,0};

const MusicPart MusicParts[] = {
  {{musicStream0, musicStream1, musicStream2, musicStream3}},
  {{musicStream4, musicStream5, musicStream6, musicStream7}},
  {{musicStream8, musicStream9, musicStream10, musicStream11}},
  {{musicStream12, musicStream13, musicStream14, musicStream11}},
  {{musicStream15, musicStream16, musicStream17, musicStream11}},
  {{musicStream18, musicStream19, musicStream20, musicStream3}},
  {{musicStream21, musicStream22, musicStream20, musicStream3}},
  {{musicStream23, musicStream24, musicStream25, musicStream26}},
  {{musicStream27, musicStream28, musicStream29, musicStream26}},
  {{musicStream30, musicStream31, musicStream32, musicStream26}},
  {{musicStream33, musicStream34, musicStream35, musicStream36}},
  {{musicStream37, musicStream38, musicStream39, musicStream40}},
  {{musicStream41, musicStream42, musicStream43, musicStream44}},
  {{musicStream45, musicStream46, musicStream47, musicStream44}},
  {{musicStream48, musicStream49, musicStream50, musicStream44}},
  {{musicStream51, musicStream52, musicStream53, musicStream36}},
  {{musicStream54, musicStream55, musicStream53, musicStream36}},
  {{musicStream56, musicStream57, musicStream58, musicStream59}},
  {{musicStream60, musicStream61, musicStream62, musicStream59}},
  {{musicStream63, musicStream64, musicStream65, musicStream59}},
  {{NULL, musicStream66, NULL, musicStream67}},
  {{NULL, musicStream68, NULL, musicStream69}},
  {{musicStream70, musicStream71, musicStream72, musicStream40}},
  {{musicStream73, musicStream74, musicStream75, musicStream76}},
  {{musicStream77, musicStream78, musicStream79, NULL}},
  {{musicStream80, musicStream81, musicStream82, NULL}},
  {{musicStream83, musicStream84, musicStream85, NULL}},
  {{musicStream86, musicStream87, musicStream88, NULL}},
};

static const uint8_t songParts0[] = {0,1,1,2,3,2,4,2,3,2,4,5,6,5,0,1,1,7,8,7,9,7,8,7,9,5,6,5,0,7,8,7,9};
static const uint8_t songParts1[] = {10,11,11,12,13,12,14,12,13,12,14,15,16,15,10,11,11,17,18,17,19,17,18,17,19,15,16,15,10,17,18,17,19};
static const uint8_t songParts2[] = {20};
static const uint8_t songParts3[] = {21};
static const uint8_t songParts4[] = {22};
static const uint8_t songParts5[] = {23};
static const uint8_t songParts6[] = {24};
static const uint8_t songParts7[] = {25};
static const uint8_t songParts8[] = {26};
static const uint8_t songParts9[] = {27};

const MusicSong MusicSongs[] = {
  {songParts0, 33, 1, 0xB2}, // GROUND
  {songParts1, 33, 1, 0xB2}, // GROUND_FAST
  {songParts2, 1, 0, 0xB1}, // UNDERGROUND
  {songParts3, 1, 0, 0xB1}, // UNDERGROUND_FAST
  {songParts4, 1, 0, 0xB2}, // STAR
  {songParts5, 1, 0, 0xB2}, // STAR_FAST
  {songParts6, 1, MUSIC_NO_LOOP, 0xA5}, // HURRY
  {songParts7, 1, MUSIC_NO_LOOP, 0xA5}, // DEATH
  {songParts8, 1, MUSIC_NO_LOOP, 0xA5}, // GAME_OVER
  {songParts9, 1, MUSIC_NO_LOOP, 0xA5}, // LEVEL_CLEAR
};

const uint16_t MusicFreqs[] = {
  1887,1992,0,1252,1297,1339,1379,1416,1486,1517,1546,1575,1602,1626,1650,1672,1693,1713,1732,1749,1767,1782,1797,1811,1824,1837,1849,1859,1870,1880,1890,1907,1899,1914,1948,1930,1936,1943,1953,1964,1968,1978,1985,1998,2006,710,1045,1155,1204,1452,1923,535,0,0,0,838,0,0,0,1140,0,0,0,0
};
