/*
 BIGMARIOTILES.H

 Big / Fire Mario. 8 tiles per 16x32 frame, row by row: TL, TR, then down.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __BigMarioTiles_h_INCLUDE
#define __BigMarioTiles_h_INCLUDE

#include <gbdk/platform.h>

#define BigMarioTilesCount 104

#define BIGMARIOTILES_STAND            0
#define BIGMARIOTILES_WALK1            8
#define BIGMARIOTILES_WALK2           16
#define BIGMARIOTILES_WALK3           24
#define BIGMARIOTILES_SKID            32
#define BIGMARIOTILES_JUMP            40
#define BIGMARIOTILES_SWIM1           48
#define BIGMARIOTILES_SWIM2           56
#define BIGMARIOTILES_SWIM3           64
#define BIGMARIOTILES_CLIMB1          72
#define BIGMARIOTILES_CLIMB2          80
#define BIGMARIOTILES_CROUCH          88
#define BIGMARIOTILES_FIRE            96

// In a switchable ROM bank: switch to BANK(BigMarioTiles) before reading it
BANKREF_EXTERN(BigMarioTiles)
extern const unsigned char BigMarioTiles[];

#endif
