/*
 CHARACTERTILES.H

 Toad and the Princess. 16x24 frames, 6 tiles row by row (TL, TR, ...).

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __CharacterTiles_h_INCLUDE
#define __CharacterTiles_h_INCLUDE

#include <gbdk/platform.h>

#define CharacterTilesCount 12

#define CHARACTERTILES_TOAD            0
#define CHARACTERTILES_PRINCESS        6

// In a switchable ROM bank: switch to BANK(CharacterTiles) before reading it
BANKREF_EXTERN(CharacterTiles)
extern const unsigned char CharacterTiles[];

#endif
