/*
 ENEMYTILES.H

 Enemies. 16x16 frames: TL, BL, TR, BR. 16x24 frames: 6 tiles row by row (TL, TR, ...). Bowser is 32x24: a FRONT and a REAR 16x24 half side by side.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __EnemyTiles_h_INCLUDE
#define __EnemyTiles_h_INCLUDE

#include <gbdk/platform.h>

#define EnemyTilesCount 167

#define ENEMYTILES_GOOMBA              0  // 16x16, walks by flipping
#define ENEMYTILES_GOOMBA_FLAT         4  // 16x16, stomped
#define ENEMYTILES_KOOPA1              8  // 16x24
#define ENEMYTILES_KOOPA2             14  // 16x24
#define ENEMYTILES_PARATROOPA1        20  // 16x24
#define ENEMYTILES_PARATROOPA2        26  // 16x24
#define ENEMYTILES_SHELL1             32  // 16x16, upside down (kicked); flip vertically for right side up
#define ENEMYTILES_SHELL2             36  // 16x16, legs out
#define ENEMYTILES_BUZZY1             40  // 16x16
#define ENEMYTILES_BUZZY2             44  // 16x16
#define ENEMYTILES_BUZZY_SHELL        48  // 16x16
#define ENEMYTILES_SPINY1             52  // 16x16
#define ENEMYTILES_SPINY2             56  // 16x16
#define ENEMYTILES_SPINY_EGG1         60  // 16x16
#define ENEMYTILES_SPINY_EGG2         64  // 16x16
#define ENEMYTILES_CHEEP1             68  // 16x16
#define ENEMYTILES_CHEEP2             72  // 16x16
#define ENEMYTILES_BLOOBER1           76  // 16x16
#define ENEMYTILES_BLOOBER2           80  // 16x24
#define ENEMYTILES_LAKITU1            86  // 16x24, in cloud
#define ENEMYTILES_LAKITU2            92  // 16x16, ducking into cloud
#define ENEMYTILES_HAMMER_BRO1        96  // 16x24
#define ENEMYTILES_HAMMER_BRO2       102  // 16x24
#define ENEMYTILES_HAMMER_BRO3       108  // 16x24
#define ENEMYTILES_HAMMER_BRO4       114  // 16x24
#define ENEMYTILES_PIRANHA1          120  // 16x24
#define ENEMYTILES_PIRANHA2          126  // 16x24
#define ENEMYTILES_PODOBOO           132  // 16x16
#define ENEMYTILES_BULLET_BILL       136  // 16x16
#define ENEMYTILES_BOWSER_FRONT1     140  // 16x24
#define ENEMYTILES_BOWSER_REAR1      146  // 16x24
#define ENEMYTILES_BOWSER_FRONT2     152  // 16x24
#define ENEMYTILES_BOWSER_REAR2      158  // 16x24
#define ENEMYTILES_BOWSER_FLAME      164  // 24x8, left to right

// In a switchable ROM bank: switch to BANK(EnemyTiles) before reading it
BANKREF_EXTERN(EnemyTiles)
extern const unsigned char EnemyTiles[];

#endif
