/*
 ITEMTILES.H

 Items and effects. 16x16 frames are TL, BL, TR, BR; the coin is 8x16 (top, bottom).

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __ItemTiles_h_INCLUDE
#define __ItemTiles_h_INCLUDE

#include <gbdk/platform.h>

#define ItemTilesCount 72

#define ITEMTILES_COIN                 0  // 4 frames x (top, bottom)
#define ITEMTILES_MUSHROOM             8  // also the 1-up mushroom
#define ITEMTILES_FLOWER              12
#define ITEMTILES_STAR                16
#define ITEMTILES_BRICK_PIECE         20  // 8x8, spun by flipping
#define ITEMTILES_SCORE               21  // "10" "20" "40" "50" "80" "0" "1U" "P" "00"
#define ITEMTILES_FIREBALL            30  // 8x8, spun by flipping
#define ITEMTILES_EXPLOSION_SMALL     31  // fireball hit / firework, 16x16
#define ITEMTILES_EXPLOSION_MEDIUM    35
#define ITEMTILES_EXPLOSION_LARGE     39
#define ITEMTILES_FLAG                43  // flagpole flag, 16x16
#define ITEMTILES_VINE                47  // 8x8 leaves, 8x8 stem
#define ITEMTILES_PLATFORM            49  // 8x8 lift / balance platform segment
#define ITEMTILES_SPRING1             50  // jumpspring, 16x24 row by row
#define ITEMTILES_SPRING2             56
#define ITEMTILES_SPRING3             62
#define ITEMTILES_CASTLE_FLAG         68  // star flag raised over the castle, 16x16

// In a switchable ROM bank: switch to BANK(ItemTiles) before reading it
BANKREF_EXTERN(ItemTiles)
extern const unsigned char ItemTiles[];

#endif
