/*
 MARIOTILES.H

 Small Mario. 4 tiles per 16x16 frame: TL, BL, TR, BR.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __MarioTiles_h_INCLUDE
#define __MarioTiles_h_INCLUDE

#include <gbdk/platform.h>

#define MarioTilesCount 48

#define MARIOTILES_STAND               0
#define MARIOTILES_WALK1               4
#define MARIOTILES_WALK2               8
#define MARIOTILES_WALK3              12
#define MARIOTILES_JUMP               16
#define MARIOTILES_SKID               20
#define MARIOTILES_DEAD               24
#define MARIOTILES_SWIM1              28
#define MARIOTILES_SWIM2              32
#define MARIOTILES_SWIM3              36
#define MARIOTILES_CLIMB1             40
#define MARIOTILES_CLIMB2             44

// In a switchable ROM bank: switch to BANK(MarioTiles) before reading it
BANKREF_EXTERN(MarioTiles)
extern const unsigned char MarioTiles[];

#endif
