/*
 MISCSPRITETILES.H

 Sprite tiles not used by any named sheet, in NES tile order. Each tile's comment gives its NES sprite tile number.

 Generated by tools/nes2gb.py from the Super Mario Bros. (NES) ROM.
 Do not edit; change the script and rerun it.
*/
#ifndef __MiscSpriteTiles_h_INCLUDE
#define __MiscSpriteTiles_h_INCLUDE

#include <gbdk/platform.h>

#define MiscSpriteTilesCount 16

#define MISCSPRITETILES_FIRST          0

// In a switchable ROM bank: switch to BANK(MiscSpriteTiles) before reading it
BANKREF_EXTERN(MiscSpriteTiles)
extern const unsigned char MiscSpriteTiles[];

#endif
